// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobs

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockAggregatesBackfillMarker creates a new instance of mockAggregatesBackfillMarker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAggregatesBackfillMarker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAggregatesBackfillMarker {
	mock := &mockAggregatesBackfillMarker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAggregatesBackfillMarker is an autogenerated mock type for the aggregatesBackfillMarker type
type mockAggregatesBackfillMarker struct {
	mock.Mock
}

type mockAggregatesBackfillMarker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAggregatesBackfillMarker) EXPECT() *mockAggregatesBackfillMarker_Expecter {
	return &mockAggregatesBackfillMarker_Expecter{mock: &_m.Mock}
}

// IsBookAggregatesBackfillDone provides a mock function for the type mockAggregatesBackfillMarker
func (_mock *mockAggregatesBackfillMarker) IsBookAggregatesBackfillDone() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsBookAggregatesBackfillDone")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockAggregatesBackfillMarker_IsBookAggregatesBackfillDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBookAggregatesBackfillDone'
type mockAggregatesBackfillMarker_IsBookAggregatesBackfillDone_Call struct {
	*mock.Call
}

// IsBookAggregatesBackfillDone is a helper method to define mock.On call
func (_e *mockAggregatesBackfillMarker_Expecter) IsBookAggregatesBackfillDone() *mockAggregatesBackfillMarker_IsBookAggregatesBackfillDone_Call {
	return &mockAggregatesBackfillMarker_IsBookAggregatesBackfillDone_Call{Call: _e.mock.On("IsBookAggregatesBackfillDone")}
}

func (_c *mockAggregatesBackfillMarker_IsBookAggregatesBackfillDone_Call) Run(run func()) *mockAggregatesBackfillMarker_IsBookAggregatesBackfillDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockAggregatesBackfillMarker_IsBookAggregatesBackfillDone_Call) Return(b bool) *mockAggregatesBackfillMarker_IsBookAggregatesBackfillDone_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockAggregatesBackfillMarker_IsBookAggregatesBackfillDone_Call) RunAndReturn(run func() bool) *mockAggregatesBackfillMarker_IsBookAggregatesBackfillDone_Call {
	_c.Call.Return(run)
	return _c
}

// MarkBookAggregatesBackfillDone provides a mock function for the type mockAggregatesBackfillMarker
func (_mock *mockAggregatesBackfillMarker) MarkBookAggregatesBackfillDone() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MarkBookAggregatesBackfillDone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAggregatesBackfillMarker_MarkBookAggregatesBackfillDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkBookAggregatesBackfillDone'
type mockAggregatesBackfillMarker_MarkBookAggregatesBackfillDone_Call struct {
	*mock.Call
}

// MarkBookAggregatesBackfillDone is a helper method to define mock.On call
func (_e *mockAggregatesBackfillMarker_Expecter) MarkBookAggregatesBackfillDone() *mockAggregatesBackfillMarker_MarkBookAggregatesBackfillDone_Call {
	return &mockAggregatesBackfillMarker_MarkBookAggregatesBackfillDone_Call{Call: _e.mock.On("MarkBookAggregatesBackfillDone")}
}

func (_c *mockAggregatesBackfillMarker_MarkBookAggregatesBackfillDone_Call) Run(run func()) *mockAggregatesBackfillMarker_MarkBookAggregatesBackfillDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockAggregatesBackfillMarker_MarkBookAggregatesBackfillDone_Call) Return(err error) *mockAggregatesBackfillMarker_MarkBookAggregatesBackfillDone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAggregatesBackfillMarker_MarkBookAggregatesBackfillDone_Call) RunAndReturn(run func() error) *mockAggregatesBackfillMarker_MarkBookAggregatesBackfillDone_Call {
	_c.Call.Return(run)
	return _c
}
