// file: tools/cmd/opsgen/main.go
// version: 1.0.0
// guid: 6195880d-76b9-48b8-bd1c-802476be4131
// last-edited: 2026-10-10

// Command opsgen writes web/src/generated/ops.ts from the run-status table in
// internal/operations/state, so the web pollers and buttons classify a status
// exactly the way the Go side does.
//
//	go run ./tools/cmd/opsgen          # regenerate (make generate-ops)
//	go run ./tools/cmd/opsgen -check   # exit 1 if the committed file is stale (make ci)
//
// Run it from the repository root. The output is deterministic (table order,
// no timestamps) so -check can byte-compare it.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/falkcorp/audiobook-organizer/internal/operations/state"
)

const defaultOut = "web/src/generated/ops.ts"

// The generated file's header. These are constants, not time.Now(): a
// timestamp would make -check fail the day after every regeneration. Bump
// genVersion and genLastEdited whenever the generated content changes.
const (
	genVersion    = "1.0.0"
	genGUID       = "ee9b10ee-5197-4ca2-8649-1aa773c69ac0"
	genLastEdited = "2026-10-10"
)

func main() {
	check := flag.Bool("check", false, "exit 1 if the output file differs from what would be generated")
	out := flag.String("out", defaultOut, "path of the generated TypeScript file")
	flag.Parse()

	want := generate()
	if *check {
		got, err := os.ReadFile(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "opsgen: read %s: %v\n", *out, err)
			os.Exit(1)
		}
		if !bytes.Equal(got, want) {
			fmt.Fprintf(os.Stderr, "opsgen: %s is stale; run `make generate-ops` and commit the result\n", *out)
			os.Exit(1)
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "opsgen: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, want, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "opsgen: write %s: %v\n", *out, err)
		os.Exit(1)
	}
}

// propFields is the Props field order in the TypeScript StatusProps type.
var propFields = []struct {
	ts  string
	get func(state.Props) bool
}{
	{"terminal", func(p state.Props) bool { return p.Terminal }},
	{"holdsSlot", func(p state.Props) bool { return p.HoldsSlot }},
	{"resumable", func(p state.Props) bool { return p.Resumable }},
	{"retryable", func(p state.Props) bool { return p.Retryable }},
	{"discardable", func(p state.Props) bool { return p.Discardable }},
	{"awaitingDecision", func(p state.Props) bool { return p.AwaitingDecision }},
	{"settled", func(p state.Props) bool { return p.Settled }},
	{"legacy", func(p state.Props) bool { return p.Legacy }},
}

func writeProps(b *bytes.Buffer, indent string, p state.Props) {
	for _, f := range propFields {
		fmt.Fprintf(b, "%s%s: %t,\n", indent, f.ts, f.get(p))
	}
}

func generate() []byte {
	var b bytes.Buffer
	w := func(s string) { b.WriteString(s) }

	w("// Code generated by tools/cmd/opsgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// file: %s\n// version: %s\n// guid: %s\n// last-edited: %s\n",
		defaultOut, genVersion, genGUID, genLastEdited)
	w(`//
// Source of truth: internal/operations/state/state.go. Regenerate with
// ` + "`make generate-ops`" + `; ` + "`make ci`" + ` fails when this file is stale.

/**
 * Every run status the v2 registry can write to an operation row, plus the
 * legacy spellings still accepted on read.
 */
export type OperationV2Status =
`)
	all := state.All()
	for i, s := range all {
		end := "\n"
		if i == len(all)-1 {
			end = ";\n"
		}
		fmt.Fprintf(&b, "  | '%s'%s", s, end)
	}
	w(`
/**
 * What a status means. See state.Props in internal/operations/state/state.go
 * for the full definitions; in short: terminal = will never run again;
 * settled = a poller has nothing more to wait for (terminal or any
 * interrupted* status); retryable/discardable = the Activity page buttons.
 */
export interface StatusProps {
`)
	for _, f := range propFields {
		fmt.Fprintf(&b, "  %s: boolean;\n", f.ts)
	}
	w("}\n\nexport const STATUS_PROPS: Record<OperationV2Status, StatusProps> = {\n")
	for _, s := range all {
		fmt.Fprintf(&b, "  %s: {\n", s)
		writeProps(&b, "    ", state.Classify(string(s)))
		w("  },\n")
	}
	w("};\n\n// An unknown status is live: not terminal, not settled.\nconst LIVE: StatusProps = {\n")
	writeProps(&b, "  ", state.Props{})
	w("};\n\n// An interrupted_* status the table does not list yet (a future resume\n// policy) is covered the day it is minted.\nconst UNKNOWN_INTERRUPTED: StatusProps = {\n")
	writeProps(&b, "  ", state.UnknownInterrupted())
	w(`};

/**
 * isInterrupted reports whether a status belongs to the interrupted family:
 * the legacy bare "interrupted" plus every "interrupted_*". Prefix-matched so
 * a status added later is covered the day it is minted.
 */
export function isInterrupted(status: string): boolean {
  return status === 'interrupted' || status.startsWith('interrupted_');
}

/**
 * classifyStatus returns the properties of a status string. Takes a plain
 * string because the legacy Operation shape types status as string.
 */
export function classifyStatus(status: string): StatusProps {
  if (Object.prototype.hasOwnProperty.call(STATUS_PROPS, status)) {
    return STATUS_PROPS[status as OperationV2Status];
  }
  return status.startsWith('interrupted_') ? UNKNOWN_INTERRUPTED : LIVE;
}

/** isTerminal: the run will never execute again (strict). */
export function isTerminal(status: string): boolean {
  return classifyStatus(status).terminal;
}

/** isSettled: a poller must stop (terminal or any interrupted* status). */
export function isSettled(status: string): boolean {
  return classifyStatus(status).settled;
}

/** isActive: the run may still progress in this session (not settled). */
export function isActive(status: string): boolean {
  return !classifyStatus(status).settled;
}

/** isRetryable: the Activity page offers Retry. */
export function isRetryable(status: string): boolean {
  return classifyStatus(status).retryable;
}

/** isDiscardable: the Activity page offers Discard. */
export function isDiscardable(status: string): boolean {
  return classifyStatus(status).discardable;
}
`)
	return b.Bytes()
}
