// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package duplicatesmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDuplicatesStore creates a new instance of MockDuplicatesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDuplicatesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDuplicatesStore {
	mock := &MockDuplicatesStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDuplicatesStore is an autogenerated mock type for the DuplicatesStore type
type MockDuplicatesStore struct {
	mock.Mock
}

type MockDuplicatesStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDuplicatesStore) EXPECT() *MockDuplicatesStore_Expecter {
	return &MockDuplicatesStore_Expecter{mock: &_m.Mock}
}

// GetBookByID provides a mock function for the type MockDuplicatesStore
func (_mock *MockDuplicatesStore) GetBookByID(id string) (*database.Book, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDuplicatesStore_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockDuplicatesStore_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - id string
func (_e *MockDuplicatesStore_Expecter) GetBookByID(id any) *MockDuplicatesStore_GetBookByID_Call {
	return &MockDuplicatesStore_GetBookByID_Call{Call: _e.mock.On("GetBookByID", id)}
}

func (_c *MockDuplicatesStore_GetBookByID_Call) Run(run func(id string)) *MockDuplicatesStore_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDuplicatesStore_GetBookByID_Call) Return(book *database.Book, err error) *MockDuplicatesStore_GetBookByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockDuplicatesStore_GetBookByID_Call) RunAndReturn(run func(id string) (*database.Book, error)) *MockDuplicatesStore_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeriesByID provides a mock function for the type MockDuplicatesStore
func (_mock *MockDuplicatesStore) GetSeriesByID(id int) (*database.Series, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSeriesByID")
	}

	var r0 *database.Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*database.Series, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *database.Series); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Series)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDuplicatesStore_GetSeriesByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeriesByID'
type MockDuplicatesStore_GetSeriesByID_Call struct {
	*mock.Call
}

// GetSeriesByID is a helper method to define mock.On call
//   - id int
func (_e *MockDuplicatesStore_Expecter) GetSeriesByID(id any) *MockDuplicatesStore_GetSeriesByID_Call {
	return &MockDuplicatesStore_GetSeriesByID_Call{Call: _e.mock.On("GetSeriesByID", id)}
}

func (_c *MockDuplicatesStore_GetSeriesByID_Call) Run(run func(id int)) *MockDuplicatesStore_GetSeriesByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDuplicatesStore_GetSeriesByID_Call) Return(series *database.Series, err error) *MockDuplicatesStore_GetSeriesByID_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *MockDuplicatesStore_GetSeriesByID_Call) RunAndReturn(run func(id int) (*database.Series, error)) *MockDuplicatesStore_GetSeriesByID_Call {
	_c.Call.Return(run)
	return _c
}
