// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockPrefixWiper creates a new instance of mockPrefixWiper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPrefixWiper(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPrefixWiper {
	mock := &mockPrefixWiper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPrefixWiper is an autogenerated mock type for the prefixWiper type
type mockPrefixWiper struct {
	mock.Mock
}

type mockPrefixWiper_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPrefixWiper) EXPECT() *mockPrefixWiper_Expecter {
	return &mockPrefixWiper_Expecter{mock: &_m.Mock}
}

// CountByPrefix provides a mock function for the type mockPrefixWiper
func (_mock *mockPrefixWiper) CountByPrefix(prefix string) (int, error) {
	ret := _mock.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for CountByPrefix")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(prefix)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrefixWiper_CountByPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByPrefix'
type mockPrefixWiper_CountByPrefix_Call struct {
	*mock.Call
}

// CountByPrefix is a helper method to define mock.On call
//   - prefix string
func (_e *mockPrefixWiper_Expecter) CountByPrefix(prefix any) *mockPrefixWiper_CountByPrefix_Call {
	return &mockPrefixWiper_CountByPrefix_Call{Call: _e.mock.On("CountByPrefix", prefix)}
}

func (_c *mockPrefixWiper_CountByPrefix_Call) Run(run func(prefix string)) *mockPrefixWiper_CountByPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockPrefixWiper_CountByPrefix_Call) Return(n int, err error) *mockPrefixWiper_CountByPrefix_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockPrefixWiper_CountByPrefix_Call) RunAndReturn(run func(prefix string) (int, error)) *mockPrefixWiper_CountByPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// WipeByPrefixes provides a mock function for the type mockPrefixWiper
func (_mock *mockPrefixWiper) WipeByPrefixes(prefixes []string) (int, error) {
	ret := _mock.Called(prefixes)

	if len(ret) == 0 {
		panic("no return value specified for WipeByPrefixes")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (int, error)); ok {
		return returnFunc(prefixes)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) int); ok {
		r0 = returnFunc(prefixes)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(prefixes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPrefixWiper_WipeByPrefixes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WipeByPrefixes'
type mockPrefixWiper_WipeByPrefixes_Call struct {
	*mock.Call
}

// WipeByPrefixes is a helper method to define mock.On call
//   - prefixes []string
func (_e *mockPrefixWiper_Expecter) WipeByPrefixes(prefixes any) *mockPrefixWiper_WipeByPrefixes_Call {
	return &mockPrefixWiper_WipeByPrefixes_Call{Call: _e.mock.On("WipeByPrefixes", prefixes)}
}

func (_c *mockPrefixWiper_WipeByPrefixes_Call) Run(run func(prefixes []string)) *mockPrefixWiper_WipeByPrefixes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockPrefixWiper_WipeByPrefixes_Call) Return(n int, err error) *mockPrefixWiper_WipeByPrefixes_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockPrefixWiper_WipeByPrefixes_Call) RunAndReturn(run func(prefixes []string) (int, error)) *mockPrefixWiper_WipeByPrefixes_Call {
	_c.Call.Return(run)
	return _c
}
