// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockWarmupWaiter creates a new instance of mockWarmupWaiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockWarmupWaiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockWarmupWaiter {
	mock := &mockWarmupWaiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockWarmupWaiter is an autogenerated mock type for the warmupWaiter type
type mockWarmupWaiter struct {
	mock.Mock
}

type mockWarmupWaiter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockWarmupWaiter) EXPECT() *mockWarmupWaiter_Expecter {
	return &mockWarmupWaiter_Expecter{mock: &_m.Mock}
}

// WaitForWarmup provides a mock function for the type mockWarmupWaiter
func (_mock *mockWarmupWaiter) WaitForWarmup() {
	_mock.Called()
	return
}

// mockWarmupWaiter_WaitForWarmup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForWarmup'
type mockWarmupWaiter_WaitForWarmup_Call struct {
	*mock.Call
}

// WaitForWarmup is a helper method to define mock.On call
func (_e *mockWarmupWaiter_Expecter) WaitForWarmup() *mockWarmupWaiter_WaitForWarmup_Call {
	return &mockWarmupWaiter_WaitForWarmup_Call{Call: _e.mock.On("WaitForWarmup")}
}

func (_c *mockWarmupWaiter_WaitForWarmup_Call) Run(run func()) *mockWarmupWaiter_WaitForWarmup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockWarmupWaiter_WaitForWarmup_Call) Return() *mockWarmupWaiter_WaitForWarmup_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockWarmupWaiter_WaitForWarmup_Call) RunAndReturn(run func()) *mockWarmupWaiter_WaitForWarmup_Call {
	_c.Run(run)
	return _c
}
