// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metadatamocks

import (
	"time"

	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetadataStore creates a new instance of MockMetadataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataStore {
	mock := &MockMetadataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataStore is an autogenerated mock type for the MetadataStore type
type MockMetadataStore struct {
	mock.Mock
}

type MockMetadataStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataStore) EXPECT() *MockMetadataStore_Expecter {
	return &MockMetadataStore_Expecter{mock: &_m.Mock}
}

// AddMetadataRejection provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) AddMetadataRejection(r database.MetadataRejection) error {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for AddMetadataRejection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(database.MetadataRejection) error); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_AddMetadataRejection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMetadataRejection'
type MockMetadataStore_AddMetadataRejection_Call struct {
	*mock.Call
}

// AddMetadataRejection is a helper method to define mock.On call
//   - r database.MetadataRejection
func (_e *MockMetadataStore_Expecter) AddMetadataRejection(r any) *MockMetadataStore_AddMetadataRejection_Call {
	return &MockMetadataStore_AddMetadataRejection_Call{Call: _e.mock.On("AddMetadataRejection", r)}
}

func (_c *MockMetadataStore_AddMetadataRejection_Call) Run(run func(r database.MetadataRejection)) *MockMetadataStore_AddMetadataRejection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.MetadataRejection
		if args[0] != nil {
			arg0 = args[0].(database.MetadataRejection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataStore_AddMetadataRejection_Call) Return(err error) *MockMetadataStore_AddMetadataRejection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_AddMetadataRejection_Call) RunAndReturn(run func(r database.MetadataRejection) error) *MockMetadataStore_AddMetadataRejection_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAuthor provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) CreateAuthor(name string) (*database.Author, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthor")
	}

	var r0 *database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Author, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Author); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_CreateAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthor'
type MockMetadataStore_CreateAuthor_Call struct {
	*mock.Call
}

// CreateAuthor is a helper method to define mock.On call
//   - name string
func (_e *MockMetadataStore_Expecter) CreateAuthor(name any) *MockMetadataStore_CreateAuthor_Call {
	return &MockMetadataStore_CreateAuthor_Call{Call: _e.mock.On("CreateAuthor", name)}
}

func (_c *MockMetadataStore_CreateAuthor_Call) Run(run func(name string)) *MockMetadataStore_CreateAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataStore_CreateAuthor_Call) Return(author *database.Author, err error) *MockMetadataStore_CreateAuthor_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockMetadataStore_CreateAuthor_Call) RunAndReturn(run func(name string) (*database.Author, error)) *MockMetadataStore_CreateAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBook provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) CreateBook(book *database.Book) (*database.Book, error) {
	ret := _mock.Called(book)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*database.Book) (*database.Book, error)); ok {
		return returnFunc(book)
	}
	if returnFunc, ok := ret.Get(0).(func(*database.Book) *database.Book); ok {
		r0 = returnFunc(book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*database.Book) error); ok {
		r1 = returnFunc(book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_CreateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBook'
type MockMetadataStore_CreateBook_Call struct {
	*mock.Call
}

// CreateBook is a helper method to define mock.On call
//   - book *database.Book
func (_e *MockMetadataStore_Expecter) CreateBook(book any) *MockMetadataStore_CreateBook_Call {
	return &MockMetadataStore_CreateBook_Call{Call: _e.mock.On("CreateBook", book)}
}

func (_c *MockMetadataStore_CreateBook_Call) Run(run func(book *database.Book)) *MockMetadataStore_CreateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.Book
		if args[0] != nil {
			arg0 = args[0].(*database.Book)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataStore_CreateBook_Call) Return(book1 *database.Book, err error) *MockMetadataStore_CreateBook_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockMetadataStore_CreateBook_Call) RunAndReturn(run func(book *database.Book) (*database.Book, error)) *MockMetadataStore_CreateBook_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOperation provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) CreateOperation(id string, opType string, folderPath *string) (*database.Operation, error) {
	ret := _mock.Called(id, opType, folderPath)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperation")
	}

	var r0 *database.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) (*database.Operation, error)); ok {
		return returnFunc(id, opType, folderPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) *database.Operation); ok {
		r0 = returnFunc(id, opType, folderPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *string) error); ok {
		r1 = returnFunc(id, opType, folderPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_CreateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOperation'
type MockMetadataStore_CreateOperation_Call struct {
	*mock.Call
}

// CreateOperation is a helper method to define mock.On call
//   - id string
//   - opType string
//   - folderPath *string
func (_e *MockMetadataStore_Expecter) CreateOperation(id any, opType any, folderPath any) *MockMetadataStore_CreateOperation_Call {
	return &MockMetadataStore_CreateOperation_Call{Call: _e.mock.On("CreateOperation", id, opType, folderPath)}
}

func (_c *MockMetadataStore_CreateOperation_Call) Run(run func(id string, opType string, folderPath *string)) *MockMetadataStore_CreateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataStore_CreateOperation_Call) Return(operation *database.Operation, err error) *MockMetadataStore_CreateOperation_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockMetadataStore_CreateOperation_Call) RunAndReturn(run func(id string, opType string, folderPath *string) (*database.Operation, error)) *MockMetadataStore_CreateOperation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSeries provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) CreateSeries(name string, authorID *int) (*database.Series, error) {
	ret := _mock.Called(name, authorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSeries")
	}

	var r0 *database.Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *int) (*database.Series, error)); ok {
		return returnFunc(name, authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *int) *database.Series); ok {
		r0 = returnFunc(name, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Series)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *int) error); ok {
		r1 = returnFunc(name, authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_CreateSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSeries'
type MockMetadataStore_CreateSeries_Call struct {
	*mock.Call
}

// CreateSeries is a helper method to define mock.On call
//   - name string
//   - authorID *int
func (_e *MockMetadataStore_Expecter) CreateSeries(name any, authorID any) *MockMetadataStore_CreateSeries_Call {
	return &MockMetadataStore_CreateSeries_Call{Call: _e.mock.On("CreateSeries", name, authorID)}
}

func (_c *MockMetadataStore_CreateSeries_Call) Run(run func(name string, authorID *int)) *MockMetadataStore_CreateSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_CreateSeries_Call) Return(series *database.Series, err error) *MockMetadataStore_CreateSeries_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *MockMetadataStore_CreateSeries_Call) RunAndReturn(run func(name string, authorID *int) (*database.Series, error)) *MockMetadataStore_CreateSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBooksCore provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) GetAllBooksCore(limit int, offset int) ([]database.BookCore, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBooksCore")
	}

	var r0 []database.BookCore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]database.BookCore, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []database.BookCore); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookCore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_GetAllBooksCore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBooksCore'
type MockMetadataStore_GetAllBooksCore_Call struct {
	*mock.Call
}

// GetAllBooksCore is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockMetadataStore_Expecter) GetAllBooksCore(limit any, offset any) *MockMetadataStore_GetAllBooksCore_Call {
	return &MockMetadataStore_GetAllBooksCore_Call{Call: _e.mock.On("GetAllBooksCore", limit, offset)}
}

func (_c *MockMetadataStore_GetAllBooksCore_Call) Run(run func(limit int, offset int)) *MockMetadataStore_GetAllBooksCore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_GetAllBooksCore_Call) Return(bookCores []database.BookCore, err error) *MockMetadataStore_GetAllBooksCore_Call {
	_c.Call.Return(bookCores, err)
	return _c
}

func (_c *MockMetadataStore_GetAllBooksCore_Call) RunAndReturn(run func(limit int, offset int) ([]database.BookCore, error)) *MockMetadataStore_GetAllBooksCore_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorByName provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) GetAuthorByName(name string) (*database.Author, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByName")
	}

	var r0 *database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Author, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Author); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_GetAuthorByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorByName'
type MockMetadataStore_GetAuthorByName_Call struct {
	*mock.Call
}

// GetAuthorByName is a helper method to define mock.On call
//   - name string
func (_e *MockMetadataStore_Expecter) GetAuthorByName(name any) *MockMetadataStore_GetAuthorByName_Call {
	return &MockMetadataStore_GetAuthorByName_Call{Call: _e.mock.On("GetAuthorByName", name)}
}

func (_c *MockMetadataStore_GetAuthorByName_Call) Run(run func(name string)) *MockMetadataStore_GetAuthorByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataStore_GetAuthorByName_Call) Return(author *database.Author, err error) *MockMetadataStore_GetAuthorByName_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockMetadataStore_GetAuthorByName_Call) RunAndReturn(run func(name string) (*database.Author, error)) *MockMetadataStore_GetAuthorByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByID provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) GetBookByID(id string) (*database.Book, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockMetadataStore_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - id string
func (_e *MockMetadataStore_Expecter) GetBookByID(id any) *MockMetadataStore_GetBookByID_Call {
	return &MockMetadataStore_GetBookByID_Call{Call: _e.mock.On("GetBookByID", id)}
}

func (_c *MockMetadataStore_GetBookByID_Call) Run(run func(id string)) *MockMetadataStore_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataStore_GetBookByID_Call) Return(book *database.Book, err error) *MockMetadataStore_GetBookByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockMetadataStore_GetBookByID_Call) RunAndReturn(run func(id string) (*database.Book, error)) *MockMetadataStore_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookSnapshots provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) GetBookSnapshots(id string, limit int) ([]database.BookSnapshot, error) {
	ret := _mock.Called(id, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetBookSnapshots")
	}

	var r0 []database.BookSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) ([]database.BookSnapshot, error)); ok {
		return returnFunc(id, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) []database.BookSnapshot); ok {
		r0 = returnFunc(id, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(id, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_GetBookSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookSnapshots'
type MockMetadataStore_GetBookSnapshots_Call struct {
	*mock.Call
}

// GetBookSnapshots is a helper method to define mock.On call
//   - id string
//   - limit int
func (_e *MockMetadataStore_Expecter) GetBookSnapshots(id any, limit any) *MockMetadataStore_GetBookSnapshots_Call {
	return &MockMetadataStore_GetBookSnapshots_Call{Call: _e.mock.On("GetBookSnapshots", id, limit)}
}

func (_c *MockMetadataStore_GetBookSnapshots_Call) Run(run func(id string, limit int)) *MockMetadataStore_GetBookSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_GetBookSnapshots_Call) Return(bookSnapshots []database.BookSnapshot, err error) *MockMetadataStore_GetBookSnapshots_Call {
	_c.Call.Return(bookSnapshots, err)
	return _c
}

func (_c *MockMetadataStore_GetBookSnapshots_Call) RunAndReturn(run func(id string, limit int) ([]database.BookSnapshot, error)) *MockMetadataStore_GetBookSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByAuthorIDCore provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) GetBooksByAuthorIDCore(authorID int) ([]database.BookCore, error) {
	ret := _mock.Called(authorID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByAuthorIDCore")
	}

	var r0 []database.BookCore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.BookCore, error)); ok {
		return returnFunc(authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.BookCore); ok {
		r0 = returnFunc(authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookCore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_GetBooksByAuthorIDCore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByAuthorIDCore'
type MockMetadataStore_GetBooksByAuthorIDCore_Call struct {
	*mock.Call
}

// GetBooksByAuthorIDCore is a helper method to define mock.On call
//   - authorID int
func (_e *MockMetadataStore_Expecter) GetBooksByAuthorIDCore(authorID any) *MockMetadataStore_GetBooksByAuthorIDCore_Call {
	return &MockMetadataStore_GetBooksByAuthorIDCore_Call{Call: _e.mock.On("GetBooksByAuthorIDCore", authorID)}
}

func (_c *MockMetadataStore_GetBooksByAuthorIDCore_Call) Run(run func(authorID int)) *MockMetadataStore_GetBooksByAuthorIDCore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataStore_GetBooksByAuthorIDCore_Call) Return(bookCores []database.BookCore, err error) *MockMetadataStore_GetBooksByAuthorIDCore_Call {
	_c.Call.Return(bookCores, err)
	return _c
}

func (_c *MockMetadataStore_GetBooksByAuthorIDCore_Call) RunAndReturn(run func(authorID int) ([]database.BookCore, error)) *MockMetadataStore_GetBooksByAuthorIDCore_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksBySeriesIDCore provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) GetBooksBySeriesIDCore(seriesID int) ([]database.BookCore, error) {
	ret := _mock.Called(seriesID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksBySeriesIDCore")
	}

	var r0 []database.BookCore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.BookCore, error)); ok {
		return returnFunc(seriesID)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.BookCore); ok {
		r0 = returnFunc(seriesID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookCore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(seriesID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_GetBooksBySeriesIDCore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksBySeriesIDCore'
type MockMetadataStore_GetBooksBySeriesIDCore_Call struct {
	*mock.Call
}

// GetBooksBySeriesIDCore is a helper method to define mock.On call
//   - seriesID int
func (_e *MockMetadataStore_Expecter) GetBooksBySeriesIDCore(seriesID any) *MockMetadataStore_GetBooksBySeriesIDCore_Call {
	return &MockMetadataStore_GetBooksBySeriesIDCore_Call{Call: _e.mock.On("GetBooksBySeriesIDCore", seriesID)}
}

func (_c *MockMetadataStore_GetBooksBySeriesIDCore_Call) Run(run func(seriesID int)) *MockMetadataStore_GetBooksBySeriesIDCore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataStore_GetBooksBySeriesIDCore_Call) Return(bookCores []database.BookCore, err error) *MockMetadataStore_GetBooksBySeriesIDCore_Call {
	_c.Call.Return(bookCores, err)
	return _c
}

func (_c *MockMetadataStore_GetBooksBySeriesIDCore_Call) RunAndReturn(run func(seriesID int) ([]database.BookCore, error)) *MockMetadataStore_GetBooksBySeriesIDCore_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadataRejections provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) GetMetadataRejections(bookID string) ([]database.MetadataRejection, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadataRejections")
	}

	var r0 []database.MetadataRejection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.MetadataRejection, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.MetadataRejection); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.MetadataRejection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_GetMetadataRejections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadataRejections'
type MockMetadataStore_GetMetadataRejections_Call struct {
	*mock.Call
}

// GetMetadataRejections is a helper method to define mock.On call
//   - bookID string
func (_e *MockMetadataStore_Expecter) GetMetadataRejections(bookID any) *MockMetadataStore_GetMetadataRejections_Call {
	return &MockMetadataStore_GetMetadataRejections_Call{Call: _e.mock.On("GetMetadataRejections", bookID)}
}

func (_c *MockMetadataStore_GetMetadataRejections_Call) Run(run func(bookID string)) *MockMetadataStore_GetMetadataRejections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataStore_GetMetadataRejections_Call) Return(metadataRejections []database.MetadataRejection, err error) *MockMetadataStore_GetMetadataRejections_Call {
	_c.Call.Return(metadataRejections, err)
	return _c
}

func (_c *MockMetadataStore_GetMetadataRejections_Call) RunAndReturn(run func(bookID string) ([]database.MetadataRejection, error)) *MockMetadataStore_GetMetadataRejections_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeriesByName provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) GetSeriesByName(name string, authorID *int) (*database.Series, error) {
	ret := _mock.Called(name, authorID)

	if len(ret) == 0 {
		panic("no return value specified for GetSeriesByName")
	}

	var r0 *database.Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *int) (*database.Series, error)); ok {
		return returnFunc(name, authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *int) *database.Series); ok {
		r0 = returnFunc(name, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Series)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *int) error); ok {
		r1 = returnFunc(name, authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_GetSeriesByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeriesByName'
type MockMetadataStore_GetSeriesByName_Call struct {
	*mock.Call
}

// GetSeriesByName is a helper method to define mock.On call
//   - name string
//   - authorID *int
func (_e *MockMetadataStore_Expecter) GetSeriesByName(name any, authorID any) *MockMetadataStore_GetSeriesByName_Call {
	return &MockMetadataStore_GetSeriesByName_Call{Call: _e.mock.On("GetSeriesByName", name, authorID)}
}

func (_c *MockMetadataStore_GetSeriesByName_Call) Run(run func(name string, authorID *int)) *MockMetadataStore_GetSeriesByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_GetSeriesByName_Call) Return(series *database.Series, err error) *MockMetadataStore_GetSeriesByName_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *MockMetadataStore_GetSeriesByName_Call) RunAndReturn(run func(name string, authorID *int) (*database.Series, error)) *MockMetadataStore_GetSeriesByName_Call {
	_c.Call.Return(run)
	return _c
}

// PruneBookSnapshots provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) PruneBookSnapshots(id string, keepCount int) (int, error) {
	ret := _mock.Called(id, keepCount)

	if len(ret) == 0 {
		panic("no return value specified for PruneBookSnapshots")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) (int, error)); ok {
		return returnFunc(id, keepCount)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) int); ok {
		r0 = returnFunc(id, keepCount)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(id, keepCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_PruneBookSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneBookSnapshots'
type MockMetadataStore_PruneBookSnapshots_Call struct {
	*mock.Call
}

// PruneBookSnapshots is a helper method to define mock.On call
//   - id string
//   - keepCount int
func (_e *MockMetadataStore_Expecter) PruneBookSnapshots(id any, keepCount any) *MockMetadataStore_PruneBookSnapshots_Call {
	return &MockMetadataStore_PruneBookSnapshots_Call{Call: _e.mock.On("PruneBookSnapshots", id, keepCount)}
}

func (_c *MockMetadataStore_PruneBookSnapshots_Call) Run(run func(id string, keepCount int)) *MockMetadataStore_PruneBookSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_PruneBookSnapshots_Call) Return(n int, err error) *MockMetadataStore_PruneBookSnapshots_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMetadataStore_PruneBookSnapshots_Call) RunAndReturn(run func(id string, keepCount int) (int, error)) *MockMetadataStore_PruneBookSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// RecordMetadataChange provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) RecordMetadataChange(record *database.MetadataChangeRecord) error {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for RecordMetadataChange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*database.MetadataChangeRecord) error); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_RecordMetadataChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordMetadataChange'
type MockMetadataStore_RecordMetadataChange_Call struct {
	*mock.Call
}

// RecordMetadataChange is a helper method to define mock.On call
//   - record *database.MetadataChangeRecord
func (_e *MockMetadataStore_Expecter) RecordMetadataChange(record any) *MockMetadataStore_RecordMetadataChange_Call {
	return &MockMetadataStore_RecordMetadataChange_Call{Call: _e.mock.On("RecordMetadataChange", record)}
}

func (_c *MockMetadataStore_RecordMetadataChange_Call) Run(run func(record *database.MetadataChangeRecord)) *MockMetadataStore_RecordMetadataChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.MetadataChangeRecord
		if args[0] != nil {
			arg0 = args[0].(*database.MetadataChangeRecord)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataStore_RecordMetadataChange_Call) Return(err error) *MockMetadataStore_RecordMetadataChange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_RecordMetadataChange_Call) RunAndReturn(run func(record *database.MetadataChangeRecord) error) *MockMetadataStore_RecordMetadataChange_Call {
	_c.Call.Return(run)
	return _c
}

// RevertBookToVersion provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) RevertBookToVersion(id string, ts time.Time) (*database.Book, error) {
	ret := _mock.Called(id, ts)

	if len(ret) == 0 {
		panic("no return value specified for RevertBookToVersion")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) (*database.Book, error)); ok {
		return returnFunc(id, ts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) *database.Book); ok {
		r0 = returnFunc(id, ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = returnFunc(id, ts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_RevertBookToVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevertBookToVersion'
type MockMetadataStore_RevertBookToVersion_Call struct {
	*mock.Call
}

// RevertBookToVersion is a helper method to define mock.On call
//   - id string
//   - ts time.Time
func (_e *MockMetadataStore_Expecter) RevertBookToVersion(id any, ts any) *MockMetadataStore_RevertBookToVersion_Call {
	return &MockMetadataStore_RevertBookToVersion_Call{Call: _e.mock.On("RevertBookToVersion", id, ts)}
}

func (_c *MockMetadataStore_RevertBookToVersion_Call) Run(run func(id string, ts time.Time)) *MockMetadataStore_RevertBookToVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_RevertBookToVersion_Call) Return(book *database.Book, err error) *MockMetadataStore_RevertBookToVersion_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockMetadataStore_RevertBookToVersion_Call) RunAndReturn(run func(id string, ts time.Time) (*database.Book, error)) *MockMetadataStore_RevertBookToVersion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBook provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) UpdateBook(id string, book *database.Book) (*database.Book, error) {
	ret := _mock.Called(id, book)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) (*database.Book, error)); ok {
		return returnFunc(id, book)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) *database.Book); ok {
		r0 = returnFunc(id, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *database.Book) error); ok {
		r1 = returnFunc(id, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_UpdateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBook'
type MockMetadataStore_UpdateBook_Call struct {
	*mock.Call
}

// UpdateBook is a helper method to define mock.On call
//   - id string
//   - book *database.Book
func (_e *MockMetadataStore_Expecter) UpdateBook(id any, book any) *MockMetadataStore_UpdateBook_Call {
	return &MockMetadataStore_UpdateBook_Call{Call: _e.mock.On("UpdateBook", id, book)}
}

func (_c *MockMetadataStore_UpdateBook_Call) Run(run func(id string, book *database.Book)) *MockMetadataStore_UpdateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *database.Book
		if args[1] != nil {
			arg1 = args[1].(*database.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_UpdateBook_Call) Return(book1 *database.Book, err error) *MockMetadataStore_UpdateBook_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockMetadataStore_UpdateBook_Call) RunAndReturn(run func(id string, book *database.Book) (*database.Book, error)) *MockMetadataStore_UpdateBook_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBookRating provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) UpdateBookRating(id string, req database.UpdateBookRatingRequest) error {
	ret := _mock.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookRating")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, database.UpdateBookRatingRequest) error); ok {
		r0 = returnFunc(id, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_UpdateBookRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBookRating'
type MockMetadataStore_UpdateBookRating_Call struct {
	*mock.Call
}

// UpdateBookRating is a helper method to define mock.On call
//   - id string
//   - req database.UpdateBookRatingRequest
func (_e *MockMetadataStore_Expecter) UpdateBookRating(id any, req any) *MockMetadataStore_UpdateBookRating_Call {
	return &MockMetadataStore_UpdateBookRating_Call{Call: _e.mock.On("UpdateBookRating", id, req)}
}

func (_c *MockMetadataStore_UpdateBookRating_Call) Run(run func(id string, req database.UpdateBookRatingRequest)) *MockMetadataStore_UpdateBookRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 database.UpdateBookRatingRequest
		if args[1] != nil {
			arg1 = args[1].(database.UpdateBookRatingRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_UpdateBookRating_Call) Return(err error) *MockMetadataStore_UpdateBookRating_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_UpdateBookRating_Call) RunAndReturn(run func(id string, req database.UpdateBookRatingRequest) error) *MockMetadataStore_UpdateBookRating_Call {
	_c.Call.Return(run)
	return _c
}
