// file: internal/authority/seed.go
// version: 1.0.0
// guid: 1fa99998-4e64-4748-854c-89c0a091fab0
// last-edited: 2026-10-04

package authority

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"regexp"

	"github.com/falkcorp/audiobook-organizer/internal/authorcredit"
)

// seedJSON is generated by scripts/gen_authority_seed.py from the owner's
// Audible library export. It holds author, narrator and publisher NAMES and
// contributor ASINs only: no title, product ASIN, series or per-title count
// (owner decision 2026-10-04). Regenerate; never hand-edit.
//
//go:embed seed/authority_seed.json
var seedJSON []byte

// Seed kinds.
const (
	SeedKindAuthor    = "author"
	SeedKindNarrator  = "narrator"
	SeedKindPublisher = "publisher"
)

// Seed is the embedded seed file. The header fields stand in for the
// version-header comment JSON cannot carry.
type Seed struct {
	File       string      `json:"file"`
	Version    string      `json:"version"`
	GUID       string      `json:"guid"`
	LastEdited string      `json:"last_edited"`
	Source     string      `json:"source"`
	Tier       Tier        `json:"tier"`
	Entries    []SeedEntry `json:"entries"`
}

// SeedEntry is one seed row. These five fields are the whole allowed shape:
// DecodeSeed rejects any other field, so a title or product ASIN cannot ride
// in under a new key.
type SeedEntry struct {
	Kind         string   `json:"kind"`
	Name         string   `json:"name"`
	ASINs        []string `json:"asins"`
	AlsoAuthor   bool     `json:"also_author"`
	AlsoNarrator bool     `json:"also_narrator"`
}

// asinRe is the shape of an Audible contributor ASIN.
var asinRe = regexp.MustCompile(`^[A-Z0-9]{10}$`)

// LoadSeed decodes and validates the embedded seed.
func LoadSeed() (*Seed, error) { return DecodeSeed(seedJSON) }

// DecodeSeed decodes a seed file strictly (unknown fields anywhere are an
// error) and validates it: source and tier, kinds, non-empty folds, no
// collective credits, ASIN shape, publishers without ASINs or role flags, and
// no duplicate (kind, fold).
func DecodeSeed(b []byte) (*Seed, error) {
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.DisallowUnknownFields()
	var s Seed
	if err := dec.Decode(&s); err != nil {
		return nil, fmt.Errorf("authority seed: decode: %w", err)
	}
	if _, err := dec.Token(); !errors.Is(err, io.EOF) {
		return nil, errors.New("authority seed: trailing data after the seed object")
	}
	if s.Source != SourceSeed {
		return nil, fmt.Errorf("authority seed: source %q, want %q", s.Source, SourceSeed)
	}
	if s.Tier != TierO {
		return nil, fmt.Errorf("authority seed: tier %q, want %q", s.Tier, TierO)
	}
	seen := make(map[string]bool, len(s.Entries))
	for i, e := range s.Entries {
		f := Fold(e.Name)
		switch {
		case f == "":
			return nil, fmt.Errorf("authority seed: entry %d: name %q folds to nothing", i, e.Name)
		case authorcredit.IsCollectiveCredit(e.Name):
			return nil, fmt.Errorf("authority seed: entry %d: %q is a collective credit", i, e.Name)
		}
		switch e.Kind {
		case SeedKindAuthor, SeedKindNarrator:
		case SeedKindPublisher:
			if len(e.ASINs) > 0 || e.AlsoAuthor || e.AlsoNarrator {
				return nil, fmt.Errorf("authority seed: entry %d: publisher %q carries person fields", i, e.Name)
			}
		default:
			return nil, fmt.Errorf("authority seed: entry %d: unknown kind %q", i, e.Kind)
		}
		for _, a := range e.ASINs {
			if !asinRe.MatchString(a) {
				return nil, fmt.Errorf("authority seed: entry %d: %q is not a contributor ASIN", i, a)
			}
		}
		k := e.Kind + ":" + f
		if seen[k] {
			return nil, fmt.Errorf("authority seed: entry %d: duplicate %s %q", i, e.Kind, e.Name)
		}
		seen[k] = true
	}
	return &s, nil
}
