// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package operationsmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOperationsStore creates a new instance of MockOperationsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationsStore {
	mock := &MockOperationsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperationsStore is an autogenerated mock type for the OperationsStore type
type MockOperationsStore struct {
	mock.Mock
}

type MockOperationsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationsStore) EXPECT() *MockOperationsStore_Expecter {
	return &MockOperationsStore_Expecter{mock: &_m.Mock}
}

// CreateAuthor provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) CreateAuthor(name string) (*database.Author, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthor")
	}

	var r0 *database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Author, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Author); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_CreateAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthor'
type MockOperationsStore_CreateAuthor_Call struct {
	*mock.Call
}

// CreateAuthor is a helper method to define mock.On call
//   - name string
func (_e *MockOperationsStore_Expecter) CreateAuthor(name any) *MockOperationsStore_CreateAuthor_Call {
	return &MockOperationsStore_CreateAuthor_Call{Call: _e.mock.On("CreateAuthor", name)}
}

func (_c *MockOperationsStore_CreateAuthor_Call) Run(run func(name string)) *MockOperationsStore_CreateAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_CreateAuthor_Call) Return(author *database.Author, err error) *MockOperationsStore_CreateAuthor_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockOperationsStore_CreateAuthor_Call) RunAndReturn(run func(name string) (*database.Author, error)) *MockOperationsStore_CreateAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNarrator provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) CreateNarrator(name string) (*database.Narrator, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateNarrator")
	}

	var r0 *database.Narrator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Narrator, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Narrator); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Narrator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_CreateNarrator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNarrator'
type MockOperationsStore_CreateNarrator_Call struct {
	*mock.Call
}

// CreateNarrator is a helper method to define mock.On call
//   - name string
func (_e *MockOperationsStore_Expecter) CreateNarrator(name any) *MockOperationsStore_CreateNarrator_Call {
	return &MockOperationsStore_CreateNarrator_Call{Call: _e.mock.On("CreateNarrator", name)}
}

func (_c *MockOperationsStore_CreateNarrator_Call) Run(run func(name string)) *MockOperationsStore_CreateNarrator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_CreateNarrator_Call) Return(narrator *database.Narrator, err error) *MockOperationsStore_CreateNarrator_Call {
	_c.Call.Return(narrator, err)
	return _c
}

func (_c *MockOperationsStore_CreateNarrator_Call) RunAndReturn(run func(name string) (*database.Narrator, error)) *MockOperationsStore_CreateNarrator_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBookTombstone provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) DeleteBookTombstone(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBookTombstone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperationsStore_DeleteBookTombstone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBookTombstone'
type MockOperationsStore_DeleteBookTombstone_Call struct {
	*mock.Call
}

// DeleteBookTombstone is a helper method to define mock.On call
//   - id string
func (_e *MockOperationsStore_Expecter) DeleteBookTombstone(id any) *MockOperationsStore_DeleteBookTombstone_Call {
	return &MockOperationsStore_DeleteBookTombstone_Call{Call: _e.mock.On("DeleteBookTombstone", id)}
}

func (_c *MockOperationsStore_DeleteBookTombstone_Call) Run(run func(id string)) *MockOperationsStore_DeleteBookTombstone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_DeleteBookTombstone_Call) Return(err error) *MockOperationsStore_DeleteBookTombstone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperationsStore_DeleteBookTombstone_Call) RunAndReturn(run func(id string) error) *MockOperationsStore_DeleteBookTombstone_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOperationsByStatus provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) DeleteOperationsByStatus(statuses []string) (int, error) {
	ret := _mock.Called(statuses)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOperationsByStatus")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (int, error)); ok {
		return returnFunc(statuses)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) int); ok {
		r0 = returnFunc(statuses)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(statuses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_DeleteOperationsByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOperationsByStatus'
type MockOperationsStore_DeleteOperationsByStatus_Call struct {
	*mock.Call
}

// DeleteOperationsByStatus is a helper method to define mock.On call
//   - statuses []string
func (_e *MockOperationsStore_Expecter) DeleteOperationsByStatus(statuses any) *MockOperationsStore_DeleteOperationsByStatus_Call {
	return &MockOperationsStore_DeleteOperationsByStatus_Call{Call: _e.mock.On("DeleteOperationsByStatus", statuses)}
}

func (_c *MockOperationsStore_DeleteOperationsByStatus_Call) Run(run func(statuses []string)) *MockOperationsStore_DeleteOperationsByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_DeleteOperationsByStatus_Call) Return(n int, err error) *MockOperationsStore_DeleteOperationsByStatus_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOperationsStore_DeleteOperationsByStatus_Call) RunAndReturn(run func(statuses []string) (int, error)) *MockOperationsStore_DeleteOperationsByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSetting provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) DeleteSetting(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperationsStore_DeleteSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSetting'
type MockOperationsStore_DeleteSetting_Call struct {
	*mock.Call
}

// DeleteSetting is a helper method to define mock.On call
//   - key string
func (_e *MockOperationsStore_Expecter) DeleteSetting(key any) *MockOperationsStore_DeleteSetting_Call {
	return &MockOperationsStore_DeleteSetting_Call{Call: _e.mock.On("DeleteSetting", key)}
}

func (_c *MockOperationsStore_DeleteSetting_Call) Run(run func(key string)) *MockOperationsStore_DeleteSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_DeleteSetting_Call) Return(err error) *MockOperationsStore_DeleteSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperationsStore_DeleteSetting_Call) RunAndReturn(run func(key string) error) *MockOperationsStore_DeleteSetting_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBooksCore provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) GetAllBooksCore(limit int, offset int) ([]database.BookCore, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBooksCore")
	}

	var r0 []database.BookCore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]database.BookCore, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []database.BookCore); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookCore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_GetAllBooksCore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBooksCore'
type MockOperationsStore_GetAllBooksCore_Call struct {
	*mock.Call
}

// GetAllBooksCore is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockOperationsStore_Expecter) GetAllBooksCore(limit any, offset any) *MockOperationsStore_GetAllBooksCore_Call {
	return &MockOperationsStore_GetAllBooksCore_Call{Call: _e.mock.On("GetAllBooksCore", limit, offset)}
}

func (_c *MockOperationsStore_GetAllBooksCore_Call) Run(run func(limit int, offset int)) *MockOperationsStore_GetAllBooksCore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperationsStore_GetAllBooksCore_Call) Return(bookCores []database.BookCore, err error) *MockOperationsStore_GetAllBooksCore_Call {
	_c.Call.Return(bookCores, err)
	return _c
}

func (_c *MockOperationsStore_GetAllBooksCore_Call) RunAndReturn(run func(limit int, offset int) ([]database.BookCore, error)) *MockOperationsStore_GetAllBooksCore_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSettings provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) GetAllSettings() ([]database.Setting, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllSettings")
	}

	var r0 []database.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Setting, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Setting); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Setting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_GetAllSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSettings'
type MockOperationsStore_GetAllSettings_Call struct {
	*mock.Call
}

// GetAllSettings is a helper method to define mock.On call
func (_e *MockOperationsStore_Expecter) GetAllSettings() *MockOperationsStore_GetAllSettings_Call {
	return &MockOperationsStore_GetAllSettings_Call{Call: _e.mock.On("GetAllSettings")}
}

func (_c *MockOperationsStore_GetAllSettings_Call) Run(run func()) *MockOperationsStore_GetAllSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOperationsStore_GetAllSettings_Call) Return(settings []database.Setting, err error) *MockOperationsStore_GetAllSettings_Call {
	_c.Call.Return(settings, err)
	return _c
}

func (_c *MockOperationsStore_GetAllSettings_Call) RunAndReturn(run func() ([]database.Setting, error)) *MockOperationsStore_GetAllSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorByID provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) GetAuthorByID(id int) (*database.Author, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByID")
	}

	var r0 *database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*database.Author, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *database.Author); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_GetAuthorByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorByID'
type MockOperationsStore_GetAuthorByID_Call struct {
	*mock.Call
}

// GetAuthorByID is a helper method to define mock.On call
//   - id int
func (_e *MockOperationsStore_Expecter) GetAuthorByID(id any) *MockOperationsStore_GetAuthorByID_Call {
	return &MockOperationsStore_GetAuthorByID_Call{Call: _e.mock.On("GetAuthorByID", id)}
}

func (_c *MockOperationsStore_GetAuthorByID_Call) Run(run func(id int)) *MockOperationsStore_GetAuthorByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_GetAuthorByID_Call) Return(author *database.Author, err error) *MockOperationsStore_GetAuthorByID_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockOperationsStore_GetAuthorByID_Call) RunAndReturn(run func(id int) (*database.Author, error)) *MockOperationsStore_GetAuthorByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorByName provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) GetAuthorByName(name string) (*database.Author, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByName")
	}

	var r0 *database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Author, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Author); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_GetAuthorByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorByName'
type MockOperationsStore_GetAuthorByName_Call struct {
	*mock.Call
}

// GetAuthorByName is a helper method to define mock.On call
//   - name string
func (_e *MockOperationsStore_Expecter) GetAuthorByName(name any) *MockOperationsStore_GetAuthorByName_Call {
	return &MockOperationsStore_GetAuthorByName_Call{Call: _e.mock.On("GetAuthorByName", name)}
}

func (_c *MockOperationsStore_GetAuthorByName_Call) Run(run func(name string)) *MockOperationsStore_GetAuthorByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_GetAuthorByName_Call) Return(author *database.Author, err error) *MockOperationsStore_GetAuthorByName_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockOperationsStore_GetAuthorByName_Call) RunAndReturn(run func(name string) (*database.Author, error)) *MockOperationsStore_GetAuthorByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByID provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) GetBookByID(id string) (*database.Book, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockOperationsStore_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - id string
func (_e *MockOperationsStore_Expecter) GetBookByID(id any) *MockOperationsStore_GetBookByID_Call {
	return &MockOperationsStore_GetBookByID_Call{Call: _e.mock.On("GetBookByID", id)}
}

func (_c *MockOperationsStore_GetBookByID_Call) Run(run func(id string)) *MockOperationsStore_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_GetBookByID_Call) Return(book *database.Book, err error) *MockOperationsStore_GetBookByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockOperationsStore_GetBookByID_Call) RunAndReturn(run func(id string) (*database.Book, error)) *MockOperationsStore_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNarratorByName provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) GetNarratorByName(name string) (*database.Narrator, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetNarratorByName")
	}

	var r0 *database.Narrator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Narrator, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Narrator); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Narrator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_GetNarratorByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNarratorByName'
type MockOperationsStore_GetNarratorByName_Call struct {
	*mock.Call
}

// GetNarratorByName is a helper method to define mock.On call
//   - name string
func (_e *MockOperationsStore_Expecter) GetNarratorByName(name any) *MockOperationsStore_GetNarratorByName_Call {
	return &MockOperationsStore_GetNarratorByName_Call{Call: _e.mock.On("GetNarratorByName", name)}
}

func (_c *MockOperationsStore_GetNarratorByName_Call) Run(run func(name string)) *MockOperationsStore_GetNarratorByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_GetNarratorByName_Call) Return(narrator *database.Narrator, err error) *MockOperationsStore_GetNarratorByName_Call {
	_c.Call.Return(narrator, err)
	return _c
}

func (_c *MockOperationsStore_GetNarratorByName_Call) RunAndReturn(run func(name string) (*database.Narrator, error)) *MockOperationsStore_GetNarratorByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperationByID provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) GetOperationByID(id string) (*database.Operation, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOperationByID")
	}

	var r0 *database.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Operation, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Operation); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_GetOperationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperationByID'
type MockOperationsStore_GetOperationByID_Call struct {
	*mock.Call
}

// GetOperationByID is a helper method to define mock.On call
//   - id string
func (_e *MockOperationsStore_Expecter) GetOperationByID(id any) *MockOperationsStore_GetOperationByID_Call {
	return &MockOperationsStore_GetOperationByID_Call{Call: _e.mock.On("GetOperationByID", id)}
}

func (_c *MockOperationsStore_GetOperationByID_Call) Run(run func(id string)) *MockOperationsStore_GetOperationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_GetOperationByID_Call) Return(operation *database.Operation, err error) *MockOperationsStore_GetOperationByID_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockOperationsStore_GetOperationByID_Call) RunAndReturn(run func(id string) (*database.Operation, error)) *MockOperationsStore_GetOperationByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperationChanges provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) GetOperationChanges(operationID string) ([]*database.OperationChange, error) {
	ret := _mock.Called(operationID)

	if len(ret) == 0 {
		panic("no return value specified for GetOperationChanges")
	}

	var r0 []*database.OperationChange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*database.OperationChange, error)); ok {
		return returnFunc(operationID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*database.OperationChange); ok {
		r0 = returnFunc(operationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*database.OperationChange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(operationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_GetOperationChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperationChanges'
type MockOperationsStore_GetOperationChanges_Call struct {
	*mock.Call
}

// GetOperationChanges is a helper method to define mock.On call
//   - operationID string
func (_e *MockOperationsStore_Expecter) GetOperationChanges(operationID any) *MockOperationsStore_GetOperationChanges_Call {
	return &MockOperationsStore_GetOperationChanges_Call{Call: _e.mock.On("GetOperationChanges", operationID)}
}

func (_c *MockOperationsStore_GetOperationChanges_Call) Run(run func(operationID string)) *MockOperationsStore_GetOperationChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_GetOperationChanges_Call) Return(operationChanges []*database.OperationChange, err error) *MockOperationsStore_GetOperationChanges_Call {
	_c.Call.Return(operationChanges, err)
	return _c
}

func (_c *MockOperationsStore_GetOperationChanges_Call) RunAndReturn(run func(operationID string) ([]*database.OperationChange, error)) *MockOperationsStore_GetOperationChanges_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentOperations provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) GetRecentOperations(limit int) ([]database.Operation, error) {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentOperations")
	}

	var r0 []database.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.Operation, error)); ok {
		return returnFunc(limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.Operation); ok {
		r0 = returnFunc(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_GetRecentOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentOperations'
type MockOperationsStore_GetRecentOperations_Call struct {
	*mock.Call
}

// GetRecentOperations is a helper method to define mock.On call
//   - limit int
func (_e *MockOperationsStore_Expecter) GetRecentOperations(limit any) *MockOperationsStore_GetRecentOperations_Call {
	return &MockOperationsStore_GetRecentOperations_Call{Call: _e.mock.On("GetRecentOperations", limit)}
}

func (_c *MockOperationsStore_GetRecentOperations_Call) Run(run func(limit int)) *MockOperationsStore_GetRecentOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_GetRecentOperations_Call) Return(operations []database.Operation, err error) *MockOperationsStore_GetRecentOperations_Call {
	_c.Call.Return(operations, err)
	return _c
}

func (_c *MockOperationsStore_GetRecentOperations_Call) RunAndReturn(run func(limit int) ([]database.Operation, error)) *MockOperationsStore_GetRecentOperations_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetting provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) GetSetting(key string) (*database.Setting, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetSetting")
	}

	var r0 *database.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Setting, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Setting); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Setting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_GetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetting'
type MockOperationsStore_GetSetting_Call struct {
	*mock.Call
}

// GetSetting is a helper method to define mock.On call
//   - key string
func (_e *MockOperationsStore_Expecter) GetSetting(key any) *MockOperationsStore_GetSetting_Call {
	return &MockOperationsStore_GetSetting_Call{Call: _e.mock.On("GetSetting", key)}
}

func (_c *MockOperationsStore_GetSetting_Call) Run(run func(key string)) *MockOperationsStore_GetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_GetSetting_Call) Return(setting *database.Setting, err error) *MockOperationsStore_GetSetting_Call {
	_c.Call.Return(setting, err)
	return _c
}

func (_c *MockOperationsStore_GetSetting_Call) RunAndReturn(run func(key string) (*database.Setting, error)) *MockOperationsStore_GetSetting_Call {
	_c.Call.Return(run)
	return _c
}

// ListBookTombstones provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) ListBookTombstones(limit int) ([]database.Book, error) {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for ListBookTombstones")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.Book, error)); ok {
		return returnFunc(limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.Book); ok {
		r0 = returnFunc(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsStore_ListBookTombstones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookTombstones'
type MockOperationsStore_ListBookTombstones_Call struct {
	*mock.Call
}

// ListBookTombstones is a helper method to define mock.On call
//   - limit int
func (_e *MockOperationsStore_Expecter) ListBookTombstones(limit any) *MockOperationsStore_ListBookTombstones_Call {
	return &MockOperationsStore_ListBookTombstones_Call{Call: _e.mock.On("ListBookTombstones", limit)}
}

func (_c *MockOperationsStore_ListBookTombstones_Call) Run(run func(limit int)) *MockOperationsStore_ListBookTombstones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsStore_ListBookTombstones_Call) Return(books []database.Book, err error) *MockOperationsStore_ListBookTombstones_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockOperationsStore_ListBookTombstones_Call) RunAndReturn(run func(limit int) ([]database.Book, error)) *MockOperationsStore_ListBookTombstones_Call {
	_c.Call.Return(run)
	return _c
}

// SetBookAuthors provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) SetBookAuthors(bookID string, authors []database.BookAuthor) error {
	ret := _mock.Called(bookID, authors)

	if len(ret) == 0 {
		panic("no return value specified for SetBookAuthors")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []database.BookAuthor) error); ok {
		r0 = returnFunc(bookID, authors)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperationsStore_SetBookAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBookAuthors'
type MockOperationsStore_SetBookAuthors_Call struct {
	*mock.Call
}

// SetBookAuthors is a helper method to define mock.On call
//   - bookID string
//   - authors []database.BookAuthor
func (_e *MockOperationsStore_Expecter) SetBookAuthors(bookID any, authors any) *MockOperationsStore_SetBookAuthors_Call {
	return &MockOperationsStore_SetBookAuthors_Call{Call: _e.mock.On("SetBookAuthors", bookID, authors)}
}

func (_c *MockOperationsStore_SetBookAuthors_Call) Run(run func(bookID string, authors []database.BookAuthor)) *MockOperationsStore_SetBookAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []database.BookAuthor
		if args[1] != nil {
			arg1 = args[1].([]database.BookAuthor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperationsStore_SetBookAuthors_Call) Return(err error) *MockOperationsStore_SetBookAuthors_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperationsStore_SetBookAuthors_Call) RunAndReturn(run func(bookID string, authors []database.BookAuthor) error) *MockOperationsStore_SetBookAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// SetBookNarrators provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) SetBookNarrators(bookID string, narrators []database.BookNarrator) error {
	ret := _mock.Called(bookID, narrators)

	if len(ret) == 0 {
		panic("no return value specified for SetBookNarrators")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []database.BookNarrator) error); ok {
		r0 = returnFunc(bookID, narrators)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperationsStore_SetBookNarrators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBookNarrators'
type MockOperationsStore_SetBookNarrators_Call struct {
	*mock.Call
}

// SetBookNarrators is a helper method to define mock.On call
//   - bookID string
//   - narrators []database.BookNarrator
func (_e *MockOperationsStore_Expecter) SetBookNarrators(bookID any, narrators any) *MockOperationsStore_SetBookNarrators_Call {
	return &MockOperationsStore_SetBookNarrators_Call{Call: _e.mock.On("SetBookNarrators", bookID, narrators)}
}

func (_c *MockOperationsStore_SetBookNarrators_Call) Run(run func(bookID string, narrators []database.BookNarrator)) *MockOperationsStore_SetBookNarrators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []database.BookNarrator
		if args[1] != nil {
			arg1 = args[1].([]database.BookNarrator)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperationsStore_SetBookNarrators_Call) Return(err error) *MockOperationsStore_SetBookNarrators_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperationsStore_SetBookNarrators_Call) RunAndReturn(run func(bookID string, narrators []database.BookNarrator) error) *MockOperationsStore_SetBookNarrators_Call {
	_c.Call.Return(run)
	return _c
}

// SetSetting provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) SetSetting(key string, value string, typ string, isSecret bool) error {
	ret := _mock.Called(key, value, typ, isSecret)

	if len(ret) == 0 {
		panic("no return value specified for SetSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, bool) error); ok {
		r0 = returnFunc(key, value, typ, isSecret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperationsStore_SetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSetting'
type MockOperationsStore_SetSetting_Call struct {
	*mock.Call
}

// SetSetting is a helper method to define mock.On call
//   - key string
//   - value string
//   - typ string
//   - isSecret bool
func (_e *MockOperationsStore_Expecter) SetSetting(key any, value any, typ any, isSecret any) *MockOperationsStore_SetSetting_Call {
	return &MockOperationsStore_SetSetting_Call{Call: _e.mock.On("SetSetting", key, value, typ, isSecret)}
}

func (_c *MockOperationsStore_SetSetting_Call) Run(run func(key string, value string, typ string, isSecret bool)) *MockOperationsStore_SetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOperationsStore_SetSetting_Call) Return(err error) *MockOperationsStore_SetSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperationsStore_SetSetting_Call) RunAndReturn(run func(key string, value string, typ string, isSecret bool) error) *MockOperationsStore_SetSetting_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOperationStatus provides a mock function for the type MockOperationsStore
func (_mock *MockOperationsStore) UpdateOperationStatus(id string, status string, progress int, total int, message string) error {
	ret := _mock.Called(id, status, progress, total, message)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOperationStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int, string) error); ok {
		r0 = returnFunc(id, status, progress, total, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperationsStore_UpdateOperationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOperationStatus'
type MockOperationsStore_UpdateOperationStatus_Call struct {
	*mock.Call
}

// UpdateOperationStatus is a helper method to define mock.On call
//   - id string
//   - status string
//   - progress int
//   - total int
//   - message string
func (_e *MockOperationsStore_Expecter) UpdateOperationStatus(id any, status any, progress any, total any, message any) *MockOperationsStore_UpdateOperationStatus_Call {
	return &MockOperationsStore_UpdateOperationStatus_Call{Call: _e.mock.On("UpdateOperationStatus", id, status, progress, total, message)}
}

func (_c *MockOperationsStore_UpdateOperationStatus_Call) Run(run func(id string, status string, progress int, total int, message string)) *MockOperationsStore_UpdateOperationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOperationsStore_UpdateOperationStatus_Call) Return(err error) *MockOperationsStore_UpdateOperationStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperationsStore_UpdateOperationStatus_Call) RunAndReturn(run func(id string, status string, progress int, total int, message string) error) *MockOperationsStore_UpdateOperationStatus_Call {
	_c.Call.Return(run)
	return _c
}
