// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlaylistStore creates a new instance of MockPlaylistStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlaylistStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlaylistStore {
	mock := &MockPlaylistStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlaylistStore is an autogenerated mock type for the PlaylistStore type
type MockPlaylistStore struct {
	mock.Mock
}

type MockPlaylistStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlaylistStore) EXPECT() *MockPlaylistStore_Expecter {
	return &MockPlaylistStore_Expecter{mock: &_m.Mock}
}

// CreateUserPlaylist provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) CreateUserPlaylist(pl *database.UserPlaylist) (*database.UserPlaylist, error) {
	ret := _mock.Called(pl)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserPlaylist")
	}

	var r0 *database.UserPlaylist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*database.UserPlaylist) (*database.UserPlaylist, error)); ok {
		return returnFunc(pl)
	}
	if returnFunc, ok := ret.Get(0).(func(*database.UserPlaylist) *database.UserPlaylist); ok {
		r0 = returnFunc(pl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserPlaylist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*database.UserPlaylist) error); ok {
		r1 = returnFunc(pl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_CreateUserPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserPlaylist'
type MockPlaylistStore_CreateUserPlaylist_Call struct {
	*mock.Call
}

// CreateUserPlaylist is a helper method to define mock.On call
//   - pl *database.UserPlaylist
func (_e *MockPlaylistStore_Expecter) CreateUserPlaylist(pl any) *MockPlaylistStore_CreateUserPlaylist_Call {
	return &MockPlaylistStore_CreateUserPlaylist_Call{Call: _e.mock.On("CreateUserPlaylist", pl)}
}

func (_c *MockPlaylistStore_CreateUserPlaylist_Call) Run(run func(pl *database.UserPlaylist)) *MockPlaylistStore_CreateUserPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.UserPlaylist
		if args[0] != nil {
			arg0 = args[0].(*database.UserPlaylist)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_CreateUserPlaylist_Call) Return(userPlaylist *database.UserPlaylist, err error) *MockPlaylistStore_CreateUserPlaylist_Call {
	_c.Call.Return(userPlaylist, err)
	return _c
}

func (_c *MockPlaylistStore_CreateUserPlaylist_Call) RunAndReturn(run func(pl *database.UserPlaylist) (*database.UserPlaylist, error)) *MockPlaylistStore_CreateUserPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserPlaylist provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) DeleteUserPlaylist(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPlaylist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlaylistStore_DeleteUserPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserPlaylist'
type MockPlaylistStore_DeleteUserPlaylist_Call struct {
	*mock.Call
}

// DeleteUserPlaylist is a helper method to define mock.On call
//   - id string
func (_e *MockPlaylistStore_Expecter) DeleteUserPlaylist(id any) *MockPlaylistStore_DeleteUserPlaylist_Call {
	return &MockPlaylistStore_DeleteUserPlaylist_Call{Call: _e.mock.On("DeleteUserPlaylist", id)}
}

func (_c *MockPlaylistStore_DeleteUserPlaylist_Call) Run(run func(id string)) *MockPlaylistStore_DeleteUserPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_DeleteUserPlaylist_Call) Return(err error) *MockPlaylistStore_DeleteUserPlaylist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlaylistStore_DeleteUserPlaylist_Call) RunAndReturn(run func(id string) error) *MockPlaylistStore_DeleteUserPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByID provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBookByID(id string) (*database.Book, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockPlaylistStore_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - id string
func (_e *MockPlaylistStore_Expecter) GetBookByID(id any) *MockPlaylistStore_GetBookByID_Call {
	return &MockPlaylistStore_GetBookByID_Call{Call: _e.mock.On("GetBookByID", id)}
}

func (_c *MockPlaylistStore_GetBookByID_Call) Run(run func(id string)) *MockPlaylistStore_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBookByID_Call) Return(book *database.Book, err error) *MockPlaylistStore_GetBookByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockPlaylistStore_GetBookByID_Call) RunAndReturn(run func(id string) (*database.Book, error)) *MockPlaylistStore_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBookState provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetUserBookState(userID string, bookID string) (*database.UserBookState, error) {
	ret := _mock.Called(userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBookState")
	}

	var r0 *database.UserBookState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*database.UserBookState, error)); ok {
		return returnFunc(userID, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *database.UserBookState); ok {
		r0 = returnFunc(userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserBookState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetUserBookState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBookState'
type MockPlaylistStore_GetUserBookState_Call struct {
	*mock.Call
}

// GetUserBookState is a helper method to define mock.On call
//   - userID string
//   - bookID string
func (_e *MockPlaylistStore_Expecter) GetUserBookState(userID any, bookID any) *MockPlaylistStore_GetUserBookState_Call {
	return &MockPlaylistStore_GetUserBookState_Call{Call: _e.mock.On("GetUserBookState", userID, bookID)}
}

func (_c *MockPlaylistStore_GetUserBookState_Call) Run(run func(userID string, bookID string)) *MockPlaylistStore_GetUserBookState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetUserBookState_Call) Return(userBookState *database.UserBookState, err error) *MockPlaylistStore_GetUserBookState_Call {
	_c.Call.Return(userBookState, err)
	return _c
}

func (_c *MockPlaylistStore_GetUserBookState_Call) RunAndReturn(run func(userID string, bookID string) (*database.UserBookState, error)) *MockPlaylistStore_GetUserBookState_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPlaylist provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetUserPlaylist(id string) (*database.UserPlaylist, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPlaylist")
	}

	var r0 *database.UserPlaylist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.UserPlaylist, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.UserPlaylist); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserPlaylist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetUserPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPlaylist'
type MockPlaylistStore_GetUserPlaylist_Call struct {
	*mock.Call
}

// GetUserPlaylist is a helper method to define mock.On call
//   - id string
func (_e *MockPlaylistStore_Expecter) GetUserPlaylist(id any) *MockPlaylistStore_GetUserPlaylist_Call {
	return &MockPlaylistStore_GetUserPlaylist_Call{Call: _e.mock.On("GetUserPlaylist", id)}
}

func (_c *MockPlaylistStore_GetUserPlaylist_Call) Run(run func(id string)) *MockPlaylistStore_GetUserPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetUserPlaylist_Call) Return(userPlaylist *database.UserPlaylist, err error) *MockPlaylistStore_GetUserPlaylist_Call {
	_c.Call.Return(userPlaylist, err)
	return _c
}

func (_c *MockPlaylistStore_GetUserPlaylist_Call) RunAndReturn(run func(id string) (*database.UserPlaylist, error)) *MockPlaylistStore_GetUserPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserPlaylistsForUser provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ListUserPlaylistsForUser(userID string, playlistType string, limit int, offset int) ([]database.UserPlaylist, int, error) {
	ret := _mock.Called(userID, playlistType, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUserPlaylistsForUser")
	}

	var r0 []database.UserPlaylist
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) ([]database.UserPlaylist, int, error)); ok {
		return returnFunc(userID, playlistType, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) []database.UserPlaylist); ok {
		r0 = returnFunc(userID, playlistType, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.UserPlaylist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int, int) int); ok {
		r1 = returnFunc(userID, playlistType, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, int, int) error); ok {
		r2 = returnFunc(userID, playlistType, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPlaylistStore_ListUserPlaylistsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserPlaylistsForUser'
type MockPlaylistStore_ListUserPlaylistsForUser_Call struct {
	*mock.Call
}

// ListUserPlaylistsForUser is a helper method to define mock.On call
//   - userID string
//   - playlistType string
//   - limit int
//   - offset int
func (_e *MockPlaylistStore_Expecter) ListUserPlaylistsForUser(userID any, playlistType any, limit any, offset any) *MockPlaylistStore_ListUserPlaylistsForUser_Call {
	return &MockPlaylistStore_ListUserPlaylistsForUser_Call{Call: _e.mock.On("ListUserPlaylistsForUser", userID, playlistType, limit, offset)}
}

func (_c *MockPlaylistStore_ListUserPlaylistsForUser_Call) Run(run func(userID string, playlistType string, limit int, offset int)) *MockPlaylistStore_ListUserPlaylistsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_ListUserPlaylistsForUser_Call) Return(userPlaylists []database.UserPlaylist, n int, err error) *MockPlaylistStore_ListUserPlaylistsForUser_Call {
	_c.Call.Return(userPlaylists, n, err)
	return _c
}

func (_c *MockPlaylistStore_ListUserPlaylistsForUser_Call) RunAndReturn(run func(userID string, playlistType string, limit int, offset int) ([]database.UserPlaylist, int, error)) *MockPlaylistStore_ListUserPlaylistsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPlaylist provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) UpdateUserPlaylist(pl *database.UserPlaylist) error {
	ret := _mock.Called(pl)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPlaylist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*database.UserPlaylist) error); ok {
		r0 = returnFunc(pl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlaylistStore_UpdateUserPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPlaylist'
type MockPlaylistStore_UpdateUserPlaylist_Call struct {
	*mock.Call
}

// UpdateUserPlaylist is a helper method to define mock.On call
//   - pl *database.UserPlaylist
func (_e *MockPlaylistStore_Expecter) UpdateUserPlaylist(pl any) *MockPlaylistStore_UpdateUserPlaylist_Call {
	return &MockPlaylistStore_UpdateUserPlaylist_Call{Call: _e.mock.On("UpdateUserPlaylist", pl)}
}

func (_c *MockPlaylistStore_UpdateUserPlaylist_Call) Run(run func(pl *database.UserPlaylist)) *MockPlaylistStore_UpdateUserPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.UserPlaylist
		if args[0] != nil {
			arg0 = args[0].(*database.UserPlaylist)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_UpdateUserPlaylist_Call) Return(err error) *MockPlaylistStore_UpdateUserPlaylist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlaylistStore_UpdateUserPlaylist_Call) RunAndReturn(run func(pl *database.UserPlaylist) error) *MockPlaylistStore_UpdateUserPlaylist_Call {
	_c.Call.Return(run)
	return _c
}
