// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetadataCacheBookStore creates a new instance of MockMetadataCacheBookStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataCacheBookStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataCacheBookStore {
	mock := &MockMetadataCacheBookStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataCacheBookStore is an autogenerated mock type for the MetadataCacheBookStore type
type MockMetadataCacheBookStore struct {
	mock.Mock
}

type MockMetadataCacheBookStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataCacheBookStore) EXPECT() *MockMetadataCacheBookStore_Expecter {
	return &MockMetadataCacheBookStore_Expecter{mock: &_m.Mock}
}

// GetAllImportPaths provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) GetAllImportPaths() ([]database.ImportPath, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllImportPaths")
	}

	var r0 []database.ImportPath
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.ImportPath, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.ImportPath); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.ImportPath)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_GetAllImportPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllImportPaths'
type MockMetadataCacheBookStore_GetAllImportPaths_Call struct {
	*mock.Call
}

// GetAllImportPaths is a helper method to define mock.On call
func (_e *MockMetadataCacheBookStore_Expecter) GetAllImportPaths() *MockMetadataCacheBookStore_GetAllImportPaths_Call {
	return &MockMetadataCacheBookStore_GetAllImportPaths_Call{Call: _e.mock.On("GetAllImportPaths")}
}

func (_c *MockMetadataCacheBookStore_GetAllImportPaths_Call) Run(run func()) *MockMetadataCacheBookStore_GetAllImportPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_GetAllImportPaths_Call) Return(importPaths []database.ImportPath, err error) *MockMetadataCacheBookStore_GetAllImportPaths_Call {
	_c.Call.Return(importPaths, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_GetAllImportPaths_Call) RunAndReturn(run func() ([]database.ImportPath, error)) *MockMetadataCacheBookStore_GetAllImportPaths_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorByID provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) GetAuthorByID(id int) (*database.Author, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByID")
	}

	var r0 *database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*database.Author, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *database.Author); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_GetAuthorByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorByID'
type MockMetadataCacheBookStore_GetAuthorByID_Call struct {
	*mock.Call
}

// GetAuthorByID is a helper method to define mock.On call
//   - id int
func (_e *MockMetadataCacheBookStore_Expecter) GetAuthorByID(id any) *MockMetadataCacheBookStore_GetAuthorByID_Call {
	return &MockMetadataCacheBookStore_GetAuthorByID_Call{Call: _e.mock.On("GetAuthorByID", id)}
}

func (_c *MockMetadataCacheBookStore_GetAuthorByID_Call) Run(run func(id int)) *MockMetadataCacheBookStore_GetAuthorByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_GetAuthorByID_Call) Return(author *database.Author, err error) *MockMetadataCacheBookStore_GetAuthorByID_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_GetAuthorByID_Call) RunAndReturn(run func(id int) (*database.Author, error)) *MockMetadataCacheBookStore_GetAuthorByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookAuthors provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) GetBookAuthors(bookID string) ([]database.BookAuthor, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookAuthors")
	}

	var r0 []database.BookAuthor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.BookAuthor, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.BookAuthor); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookAuthor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_GetBookAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookAuthors'
type MockMetadataCacheBookStore_GetBookAuthors_Call struct {
	*mock.Call
}

// GetBookAuthors is a helper method to define mock.On call
//   - bookID string
func (_e *MockMetadataCacheBookStore_Expecter) GetBookAuthors(bookID any) *MockMetadataCacheBookStore_GetBookAuthors_Call {
	return &MockMetadataCacheBookStore_GetBookAuthors_Call{Call: _e.mock.On("GetBookAuthors", bookID)}
}

func (_c *MockMetadataCacheBookStore_GetBookAuthors_Call) Run(run func(bookID string)) *MockMetadataCacheBookStore_GetBookAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_GetBookAuthors_Call) Return(bookAuthors []database.BookAuthor, err error) *MockMetadataCacheBookStore_GetBookAuthors_Call {
	_c.Call.Return(bookAuthors, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_GetBookAuthors_Call) RunAndReturn(run func(bookID string) ([]database.BookAuthor, error)) *MockMetadataCacheBookStore_GetBookAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByID provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) GetBookByID(id string) (*database.Book, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockMetadataCacheBookStore_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - id string
func (_e *MockMetadataCacheBookStore_Expecter) GetBookByID(id any) *MockMetadataCacheBookStore_GetBookByID_Call {
	return &MockMetadataCacheBookStore_GetBookByID_Call{Call: _e.mock.On("GetBookByID", id)}
}

func (_c *MockMetadataCacheBookStore_GetBookByID_Call) Run(run func(id string)) *MockMetadataCacheBookStore_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_GetBookByID_Call) Return(book *database.Book, err error) *MockMetadataCacheBookStore_GetBookByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_GetBookByID_Call) RunAndReturn(run func(id string) (*database.Book, error)) *MockMetadataCacheBookStore_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookFiles provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) GetBookFiles(bookID string) ([]database.BookFile, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookFiles")
	}

	var r0 []database.BookFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.BookFile, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.BookFile); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_GetBookFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookFiles'
type MockMetadataCacheBookStore_GetBookFiles_Call struct {
	*mock.Call
}

// GetBookFiles is a helper method to define mock.On call
//   - bookID string
func (_e *MockMetadataCacheBookStore_Expecter) GetBookFiles(bookID any) *MockMetadataCacheBookStore_GetBookFiles_Call {
	return &MockMetadataCacheBookStore_GetBookFiles_Call{Call: _e.mock.On("GetBookFiles", bookID)}
}

func (_c *MockMetadataCacheBookStore_GetBookFiles_Call) Run(run func(bookID string)) *MockMetadataCacheBookStore_GetBookFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_GetBookFiles_Call) Return(bookFiles []database.BookFile, err error) *MockMetadataCacheBookStore_GetBookFiles_Call {
	_c.Call.Return(bookFiles, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_GetBookFiles_Call) RunAndReturn(run func(bookID string) ([]database.BookFile, error)) *MockMetadataCacheBookStore_GetBookFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookFilesForIDsCore provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) GetBookFilesForIDsCore(bookIDs []string) (map[string][]database.BookFileCore, error) {
	ret := _mock.Called(bookIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetBookFilesForIDsCore")
	}

	var r0 map[string][]database.BookFileCore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (map[string][]database.BookFileCore, error)); ok {
		return returnFunc(bookIDs)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) map[string][]database.BookFileCore); ok {
		r0 = returnFunc(bookIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]database.BookFileCore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(bookIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_GetBookFilesForIDsCore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookFilesForIDsCore'
type MockMetadataCacheBookStore_GetBookFilesForIDsCore_Call struct {
	*mock.Call
}

// GetBookFilesForIDsCore is a helper method to define mock.On call
//   - bookIDs []string
func (_e *MockMetadataCacheBookStore_Expecter) GetBookFilesForIDsCore(bookIDs any) *MockMetadataCacheBookStore_GetBookFilesForIDsCore_Call {
	return &MockMetadataCacheBookStore_GetBookFilesForIDsCore_Call{Call: _e.mock.On("GetBookFilesForIDsCore", bookIDs)}
}

func (_c *MockMetadataCacheBookStore_GetBookFilesForIDsCore_Call) Run(run func(bookIDs []string)) *MockMetadataCacheBookStore_GetBookFilesForIDsCore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_GetBookFilesForIDsCore_Call) Return(stringToBookFileCores map[string][]database.BookFileCore, err error) *MockMetadataCacheBookStore_GetBookFilesForIDsCore_Call {
	_c.Call.Return(stringToBookFileCores, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_GetBookFilesForIDsCore_Call) RunAndReturn(run func(bookIDs []string) (map[string][]database.BookFileCore, error)) *MockMetadataCacheBookStore_GetBookFilesForIDsCore_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByIDs provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) GetBooksByIDs(ids []string) ([]database.Book, error) {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByIDs")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) ([]database.Book, error)); ok {
		return returnFunc(ids)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []database.Book); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_GetBooksByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByIDs'
type MockMetadataCacheBookStore_GetBooksByIDs_Call struct {
	*mock.Call
}

// GetBooksByIDs is a helper method to define mock.On call
//   - ids []string
func (_e *MockMetadataCacheBookStore_Expecter) GetBooksByIDs(ids any) *MockMetadataCacheBookStore_GetBooksByIDs_Call {
	return &MockMetadataCacheBookStore_GetBooksByIDs_Call{Call: _e.mock.On("GetBooksByIDs", ids)}
}

func (_c *MockMetadataCacheBookStore_GetBooksByIDs_Call) Run(run func(ids []string)) *MockMetadataCacheBookStore_GetBooksByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_GetBooksByIDs_Call) Return(books []database.Book, err error) *MockMetadataCacheBookStore_GetBooksByIDs_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_GetBooksByIDs_Call) RunAndReturn(run func(ids []string) ([]database.Book, error)) *MockMetadataCacheBookStore_GetBooksByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetRaw provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) GetRaw(key string) ([]byte, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetRaw")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_GetRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRaw'
type MockMetadataCacheBookStore_GetRaw_Call struct {
	*mock.Call
}

// GetRaw is a helper method to define mock.On call
//   - key string
func (_e *MockMetadataCacheBookStore_Expecter) GetRaw(key any) *MockMetadataCacheBookStore_GetRaw_Call {
	return &MockMetadataCacheBookStore_GetRaw_Call{Call: _e.mock.On("GetRaw", key)}
}

func (_c *MockMetadataCacheBookStore_GetRaw_Call) Run(run func(key string)) *MockMetadataCacheBookStore_GetRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_GetRaw_Call) Return(bytes []byte, err error) *MockMetadataCacheBookStore_GetRaw_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_GetRaw_Call) RunAndReturn(run func(key string) ([]byte, error)) *MockMetadataCacheBookStore_GetRaw_Call {
	_c.Call.Return(run)
	return _c
}

// LiveBookPathsUnderDir provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) LiveBookPathsUnderDir(dir string) (map[string]string, error) {
	ret := _mock.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for LiveBookPathsUnderDir")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]string, error)); ok {
		return returnFunc(dir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = returnFunc(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_LiveBookPathsUnderDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LiveBookPathsUnderDir'
type MockMetadataCacheBookStore_LiveBookPathsUnderDir_Call struct {
	*mock.Call
}

// LiveBookPathsUnderDir is a helper method to define mock.On call
//   - dir string
func (_e *MockMetadataCacheBookStore_Expecter) LiveBookPathsUnderDir(dir any) *MockMetadataCacheBookStore_LiveBookPathsUnderDir_Call {
	return &MockMetadataCacheBookStore_LiveBookPathsUnderDir_Call{Call: _e.mock.On("LiveBookPathsUnderDir", dir)}
}

func (_c *MockMetadataCacheBookStore_LiveBookPathsUnderDir_Call) Run(run func(dir string)) *MockMetadataCacheBookStore_LiveBookPathsUnderDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_LiveBookPathsUnderDir_Call) Return(stringToString map[string]string, err error) *MockMetadataCacheBookStore_LiveBookPathsUnderDir_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_LiveBookPathsUnderDir_Call) RunAndReturn(run func(dir string) (map[string]string, error)) *MockMetadataCacheBookStore_LiveBookPathsUnderDir_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyBook provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) ModifyBook(id string, fn func(*database.Book) error) (*database.Book, error) {
	ret := _mock.Called(id, fn)

	if len(ret) == 0 {
		panic("no return value specified for ModifyBook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, func(*database.Book) error) (*database.Book, error)); ok {
		return returnFunc(id, fn)
	}
	if returnFunc, ok := ret.Get(0).(func(string, func(*database.Book) error) *database.Book); ok {
		r0 = returnFunc(id, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, func(*database.Book) error) error); ok {
		r1 = returnFunc(id, fn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_ModifyBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyBook'
type MockMetadataCacheBookStore_ModifyBook_Call struct {
	*mock.Call
}

// ModifyBook is a helper method to define mock.On call
//   - id string
//   - fn func(*database.Book) error
func (_e *MockMetadataCacheBookStore_Expecter) ModifyBook(id any, fn any) *MockMetadataCacheBookStore_ModifyBook_Call {
	return &MockMetadataCacheBookStore_ModifyBook_Call{Call: _e.mock.On("ModifyBook", id, fn)}
}

func (_c *MockMetadataCacheBookStore_ModifyBook_Call) Run(run func(id string, fn func(*database.Book) error)) *MockMetadataCacheBookStore_ModifyBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(*database.Book) error
		if args[1] != nil {
			arg1 = args[1].(func(*database.Book) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_ModifyBook_Call) Return(book *database.Book, err error) *MockMetadataCacheBookStore_ModifyBook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_ModifyBook_Call) RunAndReturn(run func(id string, fn func(*database.Book) error) (*database.Book, error)) *MockMetadataCacheBookStore_ModifyBook_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBook provides a mock function for the type MockMetadataCacheBookStore
func (_mock *MockMetadataCacheBookStore) UpdateBook(id string, book *database.Book) (*database.Book, error) {
	ret := _mock.Called(id, book)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) (*database.Book, error)); ok {
		return returnFunc(id, book)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) *database.Book); ok {
		r0 = returnFunc(id, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *database.Book) error); ok {
		r1 = returnFunc(id, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataCacheBookStore_UpdateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBook'
type MockMetadataCacheBookStore_UpdateBook_Call struct {
	*mock.Call
}

// UpdateBook is a helper method to define mock.On call
//   - id string
//   - book *database.Book
func (_e *MockMetadataCacheBookStore_Expecter) UpdateBook(id any, book any) *MockMetadataCacheBookStore_UpdateBook_Call {
	return &MockMetadataCacheBookStore_UpdateBook_Call{Call: _e.mock.On("UpdateBook", id, book)}
}

func (_c *MockMetadataCacheBookStore_UpdateBook_Call) Run(run func(id string, book *database.Book)) *MockMetadataCacheBookStore_UpdateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *database.Book
		if args[1] != nil {
			arg1 = args[1].(*database.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataCacheBookStore_UpdateBook_Call) Return(book1 *database.Book, err error) *MockMetadataCacheBookStore_UpdateBook_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockMetadataCacheBookStore_UpdateBook_Call) RunAndReturn(run func(id string, book *database.Book) (*database.Book, error)) *MockMetadataCacheBookStore_UpdateBook_Call {
	_c.Call.Return(run)
	return _c
}
