// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReadingStore creates a new instance of MockReadingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadingStore {
	mock := &MockReadingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadingStore is an autogenerated mock type for the ReadingStore type
type MockReadingStore struct {
	mock.Mock
}

type MockReadingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadingStore) EXPECT() *MockReadingStore_Expecter {
	return &MockReadingStore_Expecter{mock: &_m.Mock}
}

// GetBookFiles provides a mock function for the type MockReadingStore
func (_mock *MockReadingStore) GetBookFiles(bookID string) ([]database.BookFile, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookFiles")
	}

	var r0 []database.BookFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.BookFile, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.BookFile); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadingStore_GetBookFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookFiles'
type MockReadingStore_GetBookFiles_Call struct {
	*mock.Call
}

// GetBookFiles is a helper method to define mock.On call
//   - bookID string
func (_e *MockReadingStore_Expecter) GetBookFiles(bookID any) *MockReadingStore_GetBookFiles_Call {
	return &MockReadingStore_GetBookFiles_Call{Call: _e.mock.On("GetBookFiles", bookID)}
}

func (_c *MockReadingStore_GetBookFiles_Call) Run(run func(bookID string)) *MockReadingStore_GetBookFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadingStore_GetBookFiles_Call) Return(bookFiles []database.BookFile, err error) *MockReadingStore_GetBookFiles_Call {
	_c.Call.Return(bookFiles, err)
	return _c
}

func (_c *MockReadingStore_GetBookFiles_Call) RunAndReturn(run func(bookID string) ([]database.BookFile, error)) *MockReadingStore_GetBookFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBookState provides a mock function for the type MockReadingStore
func (_mock *MockReadingStore) GetUserBookState(userID string, bookID string) (*database.UserBookState, error) {
	ret := _mock.Called(userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBookState")
	}

	var r0 *database.UserBookState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*database.UserBookState, error)); ok {
		return returnFunc(userID, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *database.UserBookState); ok {
		r0 = returnFunc(userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserBookState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadingStore_GetUserBookState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBookState'
type MockReadingStore_GetUserBookState_Call struct {
	*mock.Call
}

// GetUserBookState is a helper method to define mock.On call
//   - userID string
//   - bookID string
func (_e *MockReadingStore_Expecter) GetUserBookState(userID any, bookID any) *MockReadingStore_GetUserBookState_Call {
	return &MockReadingStore_GetUserBookState_Call{Call: _e.mock.On("GetUserBookState", userID, bookID)}
}

func (_c *MockReadingStore_GetUserBookState_Call) Run(run func(userID string, bookID string)) *MockReadingStore_GetUserBookState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReadingStore_GetUserBookState_Call) Return(userBookState *database.UserBookState, err error) *MockReadingStore_GetUserBookState_Call {
	_c.Call.Return(userBookState, err)
	return _c
}

func (_c *MockReadingStore_GetUserBookState_Call) RunAndReturn(run func(userID string, bookID string) (*database.UserBookState, error)) *MockReadingStore_GetUserBookState_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPosition provides a mock function for the type MockReadingStore
func (_mock *MockReadingStore) GetUserPosition(userID string, bookID string) (*database.UserPosition, error) {
	ret := _mock.Called(userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPosition")
	}

	var r0 *database.UserPosition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*database.UserPosition, error)); ok {
		return returnFunc(userID, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *database.UserPosition); ok {
		r0 = returnFunc(userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadingStore_GetUserPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPosition'
type MockReadingStore_GetUserPosition_Call struct {
	*mock.Call
}

// GetUserPosition is a helper method to define mock.On call
//   - userID string
//   - bookID string
func (_e *MockReadingStore_Expecter) GetUserPosition(userID any, bookID any) *MockReadingStore_GetUserPosition_Call {
	return &MockReadingStore_GetUserPosition_Call{Call: _e.mock.On("GetUserPosition", userID, bookID)}
}

func (_c *MockReadingStore_GetUserPosition_Call) Run(run func(userID string, bookID string)) *MockReadingStore_GetUserPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReadingStore_GetUserPosition_Call) Return(userPosition *database.UserPosition, err error) *MockReadingStore_GetUserPosition_Call {
	_c.Call.Return(userPosition, err)
	return _c
}

func (_c *MockReadingStore_GetUserPosition_Call) RunAndReturn(run func(userID string, bookID string) (*database.UserPosition, error)) *MockReadingStore_GetUserPosition_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserBookStatesByStatus provides a mock function for the type MockReadingStore
func (_mock *MockReadingStore) ListUserBookStatesByStatus(userID string, status string, limit int, offset int) ([]database.UserBookState, error) {
	ret := _mock.Called(userID, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUserBookStatesByStatus")
	}

	var r0 []database.UserBookState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) ([]database.UserBookState, error)); ok {
		return returnFunc(userID, status, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) []database.UserBookState); ok {
		r0 = returnFunc(userID, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.UserBookState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int, int) error); ok {
		r1 = returnFunc(userID, status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadingStore_ListUserBookStatesByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserBookStatesByStatus'
type MockReadingStore_ListUserBookStatesByStatus_Call struct {
	*mock.Call
}

// ListUserBookStatesByStatus is a helper method to define mock.On call
//   - userID string
//   - status string
//   - limit int
//   - offset int
func (_e *MockReadingStore_Expecter) ListUserBookStatesByStatus(userID any, status any, limit any, offset any) *MockReadingStore_ListUserBookStatesByStatus_Call {
	return &MockReadingStore_ListUserBookStatesByStatus_Call{Call: _e.mock.On("ListUserBookStatesByStatus", userID, status, limit, offset)}
}

func (_c *MockReadingStore_ListUserBookStatesByStatus_Call) Run(run func(userID string, status string, limit int, offset int)) *MockReadingStore_ListUserBookStatesByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReadingStore_ListUserBookStatesByStatus_Call) Return(userBookStates []database.UserBookState, err error) *MockReadingStore_ListUserBookStatesByStatus_Call {
	_c.Call.Return(userBookStates, err)
	return _c
}

func (_c *MockReadingStore_ListUserBookStatesByStatus_Call) RunAndReturn(run func(userID string, status string, limit int, offset int) ([]database.UserBookState, error)) *MockReadingStore_ListUserBookStatesByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserPositionsForBook provides a mock function for the type MockReadingStore
func (_mock *MockReadingStore) ListUserPositionsForBook(userID string, bookID string) ([]database.UserPosition, error) {
	ret := _mock.Called(userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserPositionsForBook")
	}

	var r0 []database.UserPosition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]database.UserPosition, error)); ok {
		return returnFunc(userID, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []database.UserPosition); ok {
		r0 = returnFunc(userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.UserPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadingStore_ListUserPositionsForBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserPositionsForBook'
type MockReadingStore_ListUserPositionsForBook_Call struct {
	*mock.Call
}

// ListUserPositionsForBook is a helper method to define mock.On call
//   - userID string
//   - bookID string
func (_e *MockReadingStore_Expecter) ListUserPositionsForBook(userID any, bookID any) *MockReadingStore_ListUserPositionsForBook_Call {
	return &MockReadingStore_ListUserPositionsForBook_Call{Call: _e.mock.On("ListUserPositionsForBook", userID, bookID)}
}

func (_c *MockReadingStore_ListUserPositionsForBook_Call) Run(run func(userID string, bookID string)) *MockReadingStore_ListUserPositionsForBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReadingStore_ListUserPositionsForBook_Call) Return(userPositions []database.UserPosition, err error) *MockReadingStore_ListUserPositionsForBook_Call {
	_c.Call.Return(userPositions, err)
	return _c
}

func (_c *MockReadingStore_ListUserPositionsForBook_Call) RunAndReturn(run func(userID string, bookID string) ([]database.UserPosition, error)) *MockReadingStore_ListUserPositionsForBook_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserBookState provides a mock function for the type MockReadingStore
func (_mock *MockReadingStore) SetUserBookState(state *database.UserBookState) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for SetUserBookState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*database.UserBookState) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReadingStore_SetUserBookState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserBookState'
type MockReadingStore_SetUserBookState_Call struct {
	*mock.Call
}

// SetUserBookState is a helper method to define mock.On call
//   - state *database.UserBookState
func (_e *MockReadingStore_Expecter) SetUserBookState(state any) *MockReadingStore_SetUserBookState_Call {
	return &MockReadingStore_SetUserBookState_Call{Call: _e.mock.On("SetUserBookState", state)}
}

func (_c *MockReadingStore_SetUserBookState_Call) Run(run func(state *database.UserBookState)) *MockReadingStore_SetUserBookState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.UserBookState
		if args[0] != nil {
			arg0 = args[0].(*database.UserBookState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadingStore_SetUserBookState_Call) Return(err error) *MockReadingStore_SetUserBookState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReadingStore_SetUserBookState_Call) RunAndReturn(run func(state *database.UserBookState) error) *MockReadingStore_SetUserBookState_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserPosition provides a mock function for the type MockReadingStore
func (_mock *MockReadingStore) SetUserPosition(userID string, bookID string, segmentID string, positionSeconds float64) error {
	ret := _mock.Called(userID, bookID, segmentID, positionSeconds)

	if len(ret) == 0 {
		panic("no return value specified for SetUserPosition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, float64) error); ok {
		r0 = returnFunc(userID, bookID, segmentID, positionSeconds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReadingStore_SetUserPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserPosition'
type MockReadingStore_SetUserPosition_Call struct {
	*mock.Call
}

// SetUserPosition is a helper method to define mock.On call
//   - userID string
//   - bookID string
//   - segmentID string
//   - positionSeconds float64
func (_e *MockReadingStore_Expecter) SetUserPosition(userID any, bookID any, segmentID any, positionSeconds any) *MockReadingStore_SetUserPosition_Call {
	return &MockReadingStore_SetUserPosition_Call{Call: _e.mock.On("SetUserPosition", userID, bookID, segmentID, positionSeconds)}
}

func (_c *MockReadingStore_SetUserPosition_Call) Run(run func(userID string, bookID string, segmentID string, positionSeconds float64)) *MockReadingStore_SetUserPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReadingStore_SetUserPosition_Call) Return(err error) *MockReadingStore_SetUserPosition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReadingStore_SetUserPosition_Call) RunAndReturn(run func(userID string, bookID string, segmentID string, positionSeconds float64) error) *MockReadingStore_SetUserPosition_Call {
	_c.Call.Return(run)
	return _c
}
