// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/database"
	"github.com/falkcorp/audiobook-organizer/internal/logger"
	"github.com/falkcorp/audiobook-organizer/internal/organizer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrganizeServicer creates a new instance of MockOrganizeServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizeServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizeServicer {
	mock := &MockOrganizeServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrganizeServicer is an autogenerated mock type for the OrganizeServicer type
type MockOrganizeServicer struct {
	mock.Mock
}

type MockOrganizeServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizeServicer) EXPECT() *MockOrganizeServicer_Expecter {
	return &MockOrganizeServicer_Expecter{mock: &_m.Mock}
}

// CreateOrganizedVersion provides a mock function for the type MockOrganizeServicer
func (_mock *MockOrganizeServicer) CreateOrganizedVersion(book *database.Book, landing *organizer.Landing, operationID string, log logger.Logger) (*database.Book, error) {
	ret := _mock.Called(book, landing, operationID, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizedVersion")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*database.Book, *organizer.Landing, string, logger.Logger) (*database.Book, error)); ok {
		return returnFunc(book, landing, operationID, log)
	}
	if returnFunc, ok := ret.Get(0).(func(*database.Book, *organizer.Landing, string, logger.Logger) *database.Book); ok {
		r0 = returnFunc(book, landing, operationID, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*database.Book, *organizer.Landing, string, logger.Logger) error); ok {
		r1 = returnFunc(book, landing, operationID, log)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizeServicer_CreateOrganizedVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganizedVersion'
type MockOrganizeServicer_CreateOrganizedVersion_Call struct {
	*mock.Call
}

// CreateOrganizedVersion is a helper method to define mock.On call
//   - book *database.Book
//   - landing *organizer.Landing
//   - operationID string
//   - log logger.Logger
func (_e *MockOrganizeServicer_Expecter) CreateOrganizedVersion(book any, landing any, operationID any, log any) *MockOrganizeServicer_CreateOrganizedVersion_Call {
	return &MockOrganizeServicer_CreateOrganizedVersion_Call{Call: _e.mock.On("CreateOrganizedVersion", book, landing, operationID, log)}
}

func (_c *MockOrganizeServicer_CreateOrganizedVersion_Call) Run(run func(book *database.Book, landing *organizer.Landing, operationID string, log logger.Logger)) *MockOrganizeServicer_CreateOrganizedVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.Book
		if args[0] != nil {
			arg0 = args[0].(*database.Book)
		}
		var arg1 *organizer.Landing
		if args[1] != nil {
			arg1 = args[1].(*organizer.Landing)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 logger.Logger
		if args[3] != nil {
			arg3 = args[3].(logger.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrganizeServicer_CreateOrganizedVersion_Call) Return(book1 *database.Book, err error) *MockOrganizeServicer_CreateOrganizedVersion_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockOrganizeServicer_CreateOrganizedVersion_Call) RunAndReturn(run func(book *database.Book, landing *organizer.Landing, operationID string, log logger.Logger) (*database.Book, error)) *MockOrganizeServicer_CreateOrganizedVersion_Call {
	_c.Call.Return(run)
	return _c
}

// OrganizeOneBook provides a mock function for the type MockOrganizeServicer
func (_mock *MockOrganizeServicer) OrganizeOneBook(org *organizer.Organizer, book *database.Book, log logger.Logger) (*organizer.Landing, error) {
	ret := _mock.Called(org, book, log)

	if len(ret) == 0 {
		panic("no return value specified for OrganizeOneBook")
	}

	var r0 *organizer.Landing
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*organizer.Organizer, *database.Book, logger.Logger) (*organizer.Landing, error)); ok {
		return returnFunc(org, book, log)
	}
	if returnFunc, ok := ret.Get(0).(func(*organizer.Organizer, *database.Book, logger.Logger) *organizer.Landing); ok {
		r0 = returnFunc(org, book, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*organizer.Landing)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*organizer.Organizer, *database.Book, logger.Logger) error); ok {
		r1 = returnFunc(org, book, log)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizeServicer_OrganizeOneBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrganizeOneBook'
type MockOrganizeServicer_OrganizeOneBook_Call struct {
	*mock.Call
}

// OrganizeOneBook is a helper method to define mock.On call
//   - org *organizer.Organizer
//   - book *database.Book
//   - log logger.Logger
func (_e *MockOrganizeServicer_Expecter) OrganizeOneBook(org any, book any, log any) *MockOrganizeServicer_OrganizeOneBook_Call {
	return &MockOrganizeServicer_OrganizeOneBook_Call{Call: _e.mock.On("OrganizeOneBook", org, book, log)}
}

func (_c *MockOrganizeServicer_OrganizeOneBook_Call) Run(run func(org *organizer.Organizer, book *database.Book, log logger.Logger)) *MockOrganizeServicer_OrganizeOneBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *organizer.Organizer
		if args[0] != nil {
			arg0 = args[0].(*organizer.Organizer)
		}
		var arg1 *database.Book
		if args[1] != nil {
			arg1 = args[1].(*database.Book)
		}
		var arg2 logger.Logger
		if args[2] != nil {
			arg2 = args[2].(logger.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizeServicer_OrganizeOneBook_Call) Return(landing *organizer.Landing, err error) *MockOrganizeServicer_OrganizeOneBook_Call {
	_c.Call.Return(landing, err)
	return _c
}

func (_c *MockOrganizeServicer_OrganizeOneBook_Call) RunAndReturn(run func(org *organizer.Organizer, book *database.Book, log logger.Logger) (*organizer.Landing, error)) *MockOrganizeServicer_OrganizeOneBook_Call {
	_c.Call.Return(run)
	return _c
}
