// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActivityService creates a new instance of MockActivityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityService {
	mock := &MockActivityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivityService is an autogenerated mock type for the ActivityService type
type MockActivityService struct {
	mock.Mock
}

type MockActivityService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityService) EXPECT() *MockActivityService_Expecter {
	return &MockActivityService_Expecter{mock: &_m.Mock}
}

// ClampSummaries provides a mock function for the type MockActivityService
func (_mock *MockActivityService) ClampSummaries(ctx context.Context, max int, dryRun bool, vacuum bool) (database.ClampSummariesResult, error) {
	ret := _mock.Called(ctx, max, dryRun, vacuum)

	if len(ret) == 0 {
		panic("no return value specified for ClampSummaries")
	}

	var r0 database.ClampSummariesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool, bool) (database.ClampSummariesResult, error)); ok {
		return returnFunc(ctx, max, dryRun, vacuum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool, bool) database.ClampSummariesResult); ok {
		r0 = returnFunc(ctx, max, dryRun, vacuum)
	} else {
		r0 = ret.Get(0).(database.ClampSummariesResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool, bool) error); ok {
		r1 = returnFunc(ctx, max, dryRun, vacuum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityService_ClampSummaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClampSummaries'
type MockActivityService_ClampSummaries_Call struct {
	*mock.Call
}

// ClampSummaries is a helper method to define mock.On call
//   - ctx context.Context
//   - max int
//   - dryRun bool
//   - vacuum bool
func (_e *MockActivityService_Expecter) ClampSummaries(ctx any, max any, dryRun any, vacuum any) *MockActivityService_ClampSummaries_Call {
	return &MockActivityService_ClampSummaries_Call{Call: _e.mock.On("ClampSummaries", ctx, max, dryRun, vacuum)}
}

func (_c *MockActivityService_ClampSummaries_Call) Run(run func(ctx context.Context, max int, dryRun bool, vacuum bool)) *MockActivityService_ClampSummaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockActivityService_ClampSummaries_Call) Return(clampSummariesResult database.ClampSummariesResult, err error) *MockActivityService_ClampSummaries_Call {
	_c.Call.Return(clampSummariesResult, err)
	return _c
}

func (_c *MockActivityService_ClampSummaries_Call) RunAndReturn(run func(ctx context.Context, max int, dryRun bool, vacuum bool) (database.ClampSummariesResult, error)) *MockActivityService_ClampSummaries_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistinctSources provides a mock function for the type MockActivityService
func (_mock *MockActivityService) GetDistinctSources(ctx context.Context, filter database.ActivityFilter) ([]database.SourceCount, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetDistinctSources")
	}

	var r0 []database.SourceCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.ActivityFilter) ([]database.SourceCount, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.ActivityFilter) []database.SourceCount); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.SourceCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.ActivityFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityService_GetDistinctSources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistinctSources'
type MockActivityService_GetDistinctSources_Call struct {
	*mock.Call
}

// GetDistinctSources is a helper method to define mock.On call
//   - ctx context.Context
//   - filter database.ActivityFilter
func (_e *MockActivityService_Expecter) GetDistinctSources(ctx any, filter any) *MockActivityService_GetDistinctSources_Call {
	return &MockActivityService_GetDistinctSources_Call{Call: _e.mock.On("GetDistinctSources", ctx, filter)}
}

func (_c *MockActivityService_GetDistinctSources_Call) Run(run func(ctx context.Context, filter database.ActivityFilter)) *MockActivityService_GetDistinctSources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.ActivityFilter
		if args[1] != nil {
			arg1 = args[1].(database.ActivityFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityService_GetDistinctSources_Call) Return(sourceCounts []database.SourceCount, err error) *MockActivityService_GetDistinctSources_Call {
	_c.Call.Return(sourceCounts, err)
	return _c
}

func (_c *MockActivityService_GetDistinctSources_Call) RunAndReturn(run func(ctx context.Context, filter database.ActivityFilter) ([]database.SourceCount, error)) *MockActivityService_GetDistinctSources_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockActivityService
func (_mock *MockActivityService) Query(ctx context.Context, filter database.ActivityFilter) ([]database.ActivityEntry, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []database.ActivityEntry
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.ActivityFilter) ([]database.ActivityEntry, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.ActivityFilter) []database.ActivityEntry); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.ActivityEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.ActivityFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, database.ActivityFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockActivityService_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockActivityService_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - filter database.ActivityFilter
func (_e *MockActivityService_Expecter) Query(ctx any, filter any) *MockActivityService_Query_Call {
	return &MockActivityService_Query_Call{Call: _e.mock.On("Query", ctx, filter)}
}

func (_c *MockActivityService_Query_Call) Run(run func(ctx context.Context, filter database.ActivityFilter)) *MockActivityService_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.ActivityFilter
		if args[1] != nil {
			arg1 = args[1].(database.ActivityFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityService_Query_Call) Return(activityEntrys []database.ActivityEntry, n int, err error) *MockActivityService_Query_Call {
	_c.Call.Return(activityEntrys, n, err)
	return _c
}

func (_c *MockActivityService_Query_Call) RunAndReturn(run func(ctx context.Context, filter database.ActivityFilter) ([]database.ActivityEntry, int, error)) *MockActivityService_Query_Call {
	_c.Call.Return(run)
	return _c
}
