// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockKeyCounter creates a new instance of mockKeyCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockKeyCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockKeyCounter {
	mock := &mockKeyCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockKeyCounter is an autogenerated mock type for the keyCounter type
type mockKeyCounter struct {
	mock.Mock
}

type mockKeyCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockKeyCounter) EXPECT() *mockKeyCounter_Expecter {
	return &mockKeyCounter_Expecter{mock: &_m.Mock}
}

// KeyCount provides a mock function for the type mockKeyCounter
func (_mock *mockKeyCounter) KeyCount() (int64, uint64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KeyCount")
	}

	var r0 int64
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (int64, uint64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() uint64); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockKeyCounter_KeyCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyCount'
type mockKeyCounter_KeyCount_Call struct {
	*mock.Call
}

// KeyCount is a helper method to define mock.On call
func (_e *mockKeyCounter_Expecter) KeyCount() *mockKeyCounter_KeyCount_Call {
	return &mockKeyCounter_KeyCount_Call{Call: _e.mock.On("KeyCount")}
}

func (_c *mockKeyCounter_KeyCount_Call) Run(run func()) *mockKeyCounter_KeyCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockKeyCounter_KeyCount_Call) Return(count int64, sizeBytes uint64, err error) *mockKeyCounter_KeyCount_Call {
	_c.Call.Return(count, sizeBytes, err)
	return _c
}

func (_c *mockKeyCounter_KeyCount_Call) RunAndReturn(run func() (int64, uint64, error)) *mockKeyCounter_KeyCount_Call {
	_c.Call.Return(run)
	return _c
}
