// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audiobooksmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/metafetch"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetadataFetchService creates a new instance of MockMetadataFetchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataFetchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataFetchService {
	mock := &MockMetadataFetchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataFetchService is an autogenerated mock type for the MetadataFetchService type
type MockMetadataFetchService struct {
	mock.Mock
}

type MockMetadataFetchService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataFetchService) EXPECT() *MockMetadataFetchService_Expecter {
	return &MockMetadataFetchService_Expecter{mock: &_m.Mock}
}

// InvalidateCachedCandidates provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) InvalidateCachedCandidates(bookID string) error {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateCachedCandidates")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(bookID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataFetchService_InvalidateCachedCandidates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateCachedCandidates'
type MockMetadataFetchService_InvalidateCachedCandidates_Call struct {
	*mock.Call
}

// InvalidateCachedCandidates is a helper method to define mock.On call
//   - bookID string
func (_e *MockMetadataFetchService_Expecter) InvalidateCachedCandidates(bookID any) *MockMetadataFetchService_InvalidateCachedCandidates_Call {
	return &MockMetadataFetchService_InvalidateCachedCandidates_Call{Call: _e.mock.On("InvalidateCachedCandidates", bookID)}
}

func (_c *MockMetadataFetchService_InvalidateCachedCandidates_Call) Run(run func(bookID string)) *MockMetadataFetchService_InvalidateCachedCandidates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_InvalidateCachedCandidates_Call) Return(err error) *MockMetadataFetchService_InvalidateCachedCandidates_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataFetchService_InvalidateCachedCandidates_Call) RunAndReturn(run func(bookID string) error) *MockMetadataFetchService_InvalidateCachedCandidates_Call {
	_c.Call.Return(run)
	return _c
}

// UndoFieldChange provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) UndoFieldChange(bookID string, field string) (*metafetch.UndoApplyResult, error) {
	ret := _mock.Called(bookID, field)

	if len(ret) == 0 {
		panic("no return value specified for UndoFieldChange")
	}

	var r0 *metafetch.UndoApplyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*metafetch.UndoApplyResult, error)); ok {
		return returnFunc(bookID, field)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *metafetch.UndoApplyResult); ok {
		r0 = returnFunc(bookID, field)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metafetch.UndoApplyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(bookID, field)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataFetchService_UndoFieldChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UndoFieldChange'
type MockMetadataFetchService_UndoFieldChange_Call struct {
	*mock.Call
}

// UndoFieldChange is a helper method to define mock.On call
//   - bookID string
//   - field string
func (_e *MockMetadataFetchService_Expecter) UndoFieldChange(bookID any, field any) *MockMetadataFetchService_UndoFieldChange_Call {
	return &MockMetadataFetchService_UndoFieldChange_Call{Call: _e.mock.On("UndoFieldChange", bookID, field)}
}

func (_c *MockMetadataFetchService_UndoFieldChange_Call) Run(run func(bookID string, field string)) *MockMetadataFetchService_UndoFieldChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_UndoFieldChange_Call) Return(undoApplyResult *metafetch.UndoApplyResult, err error) *MockMetadataFetchService_UndoFieldChange_Call {
	_c.Call.Return(undoApplyResult, err)
	return _c
}

func (_c *MockMetadataFetchService_UndoFieldChange_Call) RunAndReturn(run func(bookID string, field string) (*metafetch.UndoApplyResult, error)) *MockMetadataFetchService_UndoFieldChange_Call {
	_c.Call.Return(run)
	return _c
}

// UndoLastApply provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) UndoLastApply(bookID string) (*metafetch.UndoApplyResult, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for UndoLastApply")
	}

	var r0 *metafetch.UndoApplyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*metafetch.UndoApplyResult, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *metafetch.UndoApplyResult); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metafetch.UndoApplyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataFetchService_UndoLastApply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UndoLastApply'
type MockMetadataFetchService_UndoLastApply_Call struct {
	*mock.Call
}

// UndoLastApply is a helper method to define mock.On call
//   - bookID string
func (_e *MockMetadataFetchService_Expecter) UndoLastApply(bookID any) *MockMetadataFetchService_UndoLastApply_Call {
	return &MockMetadataFetchService_UndoLastApply_Call{Call: _e.mock.On("UndoLastApply", bookID)}
}

func (_c *MockMetadataFetchService_UndoLastApply_Call) Run(run func(bookID string)) *MockMetadataFetchService_UndoLastApply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_UndoLastApply_Call) Return(undoApplyResult *metafetch.UndoApplyResult, err error) *MockMetadataFetchService_UndoLastApply_Call {
	_c.Call.Return(undoApplyResult, err)
	return _c
}

func (_c *MockMetadataFetchService_UndoLastApply_Call) RunAndReturn(run func(bookID string) (*metafetch.UndoApplyResult, error)) *MockMetadataFetchService_UndoLastApply_Call {
	_c.Call.Return(run)
	return _c
}
