// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audiobooksmocks

import (
	"context"

	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAudiobookUpdater creates a new instance of MockAudiobookUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudiobookUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudiobookUpdater {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAudiobookUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAudiobookUpdater is an autogenerated mock type for the AudiobookUpdater type
type MockAudiobookUpdater struct {
	mock.Mock
}

type MockAudiobookUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudiobookUpdater) EXPECT() *MockAudiobookUpdater_Expecter {
	return &MockAudiobookUpdater_Expecter{mock: &_m.Mock}
}

// UpdateAudiobookWithWarnings provides a mock function for the type MockAudiobookUpdater
func (_mock *MockAudiobookUpdater) UpdateAudiobookWithWarnings(ctx context.Context, id string, payload map[string]any) (*database.Book, []string, error) {
	ret := _mock.Called(ctx, id, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAudiobookWithWarnings")
	}

	var r0 *database.Book
	var r1 []string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) (*database.Book, []string, error)); ok {
		return returnFunc(ctx, id, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) *database.Book); ok {
		r0 = returnFunc(ctx, id, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]any) []string); ok {
		r1 = returnFunc(ctx, id, payload)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, map[string]any) error); ok {
		r2 = returnFunc(ctx, id, payload)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAudiobookUpdater_UpdateAudiobookWithWarnings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAudiobookWithWarnings'
type MockAudiobookUpdater_UpdateAudiobookWithWarnings_Call struct {
	*mock.Call
}

// UpdateAudiobookWithWarnings is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - payload map[string]any
func (_e *MockAudiobookUpdater_Expecter) UpdateAudiobookWithWarnings(ctx any, id any, payload any) *MockAudiobookUpdater_UpdateAudiobookWithWarnings_Call {
	return &MockAudiobookUpdater_UpdateAudiobookWithWarnings_Call{Call: _e.mock.On("UpdateAudiobookWithWarnings", ctx, id, payload)}
}

func (_c *MockAudiobookUpdater_UpdateAudiobookWithWarnings_Call) Run(run func(ctx context.Context, id string, payload map[string]any)) *MockAudiobookUpdater_UpdateAudiobookWithWarnings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAudiobookUpdater_UpdateAudiobookWithWarnings_Call) Return(book *database.Book, strings []string, err error) *MockAudiobookUpdater_UpdateAudiobookWithWarnings_Call {
	_c.Call.Return(book, strings, err)
	return _c
}

func (_c *MockAudiobookUpdater_UpdateAudiobookWithWarnings_Call) RunAndReturn(run func(ctx context.Context, id string, payload map[string]any) (*database.Book, []string, error)) *MockAudiobookUpdater_UpdateAudiobookWithWarnings_Call {
	_c.Call.Return(run)
	return _c
}
