#!/bin/bash
# file: scripts/setup-git-hooks.sh
# version: 1.1.0
# guid: e8c4b7a2-1f3d-44e7-9c5e-8f2d1b4a9e3c
# last-edited: 2026-07-03
# Set up git pre-commit hook to prevent accidentally committing .api-token

HOOK_DIR="$(git rev-parse --git-dir)/hooks"
HOOK_FILE="$HOOK_DIR/pre-commit"

# Create hooks directory if it doesn't exist
mkdir -p "$HOOK_DIR"

# Create pre-commit hook
cat > "$HOOK_FILE" <<'EOF'
#!/bin/bash
# Pre-commit hook: prevent .api-token from being committed

PROTECTED_FILES=(
    ".api-token"
    ".claude/.api-token"
    ".bootstrap-token"
    ".readonly-key"
    ".claude/.credentials/"
)

STAGED_FILES=$(git diff --cached --name-only)

for FILE in "${PROTECTED_FILES[@]}"; do
    if [[ "$FILE" == */ ]]; then
        ESCAPED_FILE=$(printf '%s\n' "$FILE" | sed 's/[.[\*^$]/\\&/g')
        MATCH=$(echo "$STAGED_FILES" | grep -q "^$ESCAPED_FILE" && echo yes)
    else
        ESCAPED_FILE=$(printf '%s\n' "$FILE" | sed 's/[.[\*^$]/\\&/g')
        MATCH=$(echo "$STAGED_FILES" | grep -q "^$ESCAPED_FILE$" && echo yes)
    fi
    if [[ "$MATCH" == "yes" ]]; then
        echo "❌ Error: Attempting to commit protected file/path: $FILE"
        echo ""
        echo "This file contains secrets and should never be committed."
        echo "It's in .gitignore and is auto-generated by scripts."
        echo ""
        echo "To unstage this file:"
        echo "  git reset HEAD $FILE"
        echo ""
        exit 1
    fi
done

exit 0
EOF

# Make hook executable
chmod +x "$HOOK_FILE"

echo "✅ Git pre-commit hook installed at $HOOK_FILE"
echo ""
echo "Protected files and directories:"
echo "  - .api-token (shared API key across worktrees)"
echo "  - .claude/.api-token (same as above)"
echo "  - .bootstrap-token (temporary bootstrap auth token)"
echo "  - .readonly-key (startup read-only API key)"
echo "  - .claude/.credentials/ (per-worktree username/password)"
echo ""
echo "The hook will prevent these from being committed."
echo "If you accidentally stage one, you'll get an error message."
echo ""
echo "To manage worktree credentials, use:"
echo "  ./scripts/manage-credentials.sh --help"
