#!/bin/bash
# file: scripts/setup-git-hooks.sh
# version: 1.2.0
# guid: e8c4b7a2-1f3d-44e7-9c5e-8f2d1b4a9e3c
# last-edited: 2026-07-17
# Set up git pre-commit hook to prevent accidentally committing .api-token
#
# Uses --git-common-dir (NOT --git-dir): in a linked worktree, --git-dir
# resolves to .git/worktrees/<name>, whose hooks/ directory git never
# consults — a hook installed there silently never fires. The common dir's
# hooks/ applies to the main checkout AND every worktree.

HOOK_DIR="$(git rev-parse --path-format=absolute --git-common-dir)/hooks"
HOOK_FILE="$HOOK_DIR/pre-commit"

# Create hooks directory if it doesn't exist
mkdir -p "$HOOK_DIR"

# Create pre-commit hook
cat > "$HOOK_FILE" <<'EOF'
#!/bin/bash
# Pre-commit hook: prevent credentials/secrets from being committed

PROTECTED_FILES=(
    ".api-token"
    ".claude/.api-token"
    ".bootstrap-token"
    ".readonly-key"
    ".claude/.credentials/"
)

STAGED_FILES=$(git diff --cached --name-only)

for FILE in "${PROTECTED_FILES[@]}"; do
    if [[ "$FILE" == */ ]]; then
        ESCAPED_FILE=$(printf '%s\n' "$FILE" | sed 's/[.[\*^$]/\\&/g')
        MATCH=$(echo "$STAGED_FILES" | grep -q "^$ESCAPED_FILE" && echo yes)
    else
        ESCAPED_FILE=$(printf '%s\n' "$FILE" | sed 's/[.[\*^$]/\\&/g')
        MATCH=$(echo "$STAGED_FILES" | grep -q "^$ESCAPED_FILE$" && echo yes)
    fi
    if [[ "$MATCH" == "yes" ]]; then
        echo "❌ Error: Attempting to commit protected file/path: $FILE"
        echo ""
        echo "This file contains secrets and should never be committed."
        echo "It's in .gitignore and is auto-generated by scripts."
        echo ""
        echo "To unstage this file:"
        echo "  git reset HEAD $FILE"
        echo ""
        exit 1
    fi
done

# Content scan: block staged diffs that ADD API tokens or internal IPs.
# Patterns: abk_ API keys, and 172.16.x.x internal-network addresses.
# NOTE: all greps use -E (ERE) — in BRE, '\+' is a repetition operator and
# '^\+\+\+ ' errors out ("repetition-operator operand invalid").
SECRET_RE='abk_[A-Za-z0-9]{16,}|172\.16\.[0-9]{1,3}\.[0-9]{1,3}'
ADDED_SECRETS=$(git diff --cached --unified=0 --no-color \
    | grep -E '^\+' | grep -Ev '^\+\+\+ ' | grep -E "$SECRET_RE")
if [[ -n "$ADDED_SECRETS" ]]; then
    echo "❌ Error: staged changes add content matching a secret/internal-IP pattern:"
    echo ""
    echo "$ADDED_SECRETS" | head -10
    echo ""
    echo "This is a public repo — API tokens (abk_...) and internal network"
    echo "addresses (172.16.x.x) must never be committed. Replace with an env"
    echo "variable or a placeholder like https://<server>:8484."
    echo ""
    echo "If this is a deliberate false positive, bypass once with:"
    echo "  git commit --no-verify"
    echo ""
    exit 1
fi

exit 0
EOF

# Make hook executable
chmod +x "$HOOK_FILE"

echo "✅ Git pre-commit hook installed at $HOOK_FILE"
echo ""
echo "Protected files and directories:"
echo "  - .api-token (shared API key across worktrees)"
echo "  - .claude/.api-token (same as above)"
echo "  - .bootstrap-token (temporary bootstrap auth token)"
echo "  - .readonly-key (startup read-only API key)"
echo "  - .claude/.credentials/ (per-worktree username/password)"
echo ""
echo "Staged-content scan also blocks diffs that ADD:"
echo "  - API tokens matching abk_<16+ alphanumerics>"
echo "  - internal IPs matching 172.16.x.x"
echo "(bypass a false positive with: git commit --no-verify)"
echo ""
echo "The hook is installed in the COMMON git dir, so it fires for the main"
echo "checkout and every linked worktree."
echo ""
echo "To manage worktree credentials, use:"
echo "  ./scripts/manage-credentials.sh --help"
