#!/usr/bin/env python3
# file: docs/agent-tasks/todo-completion-2026-09/state/tools/build_matrix.py
# version: 1.4.0
# guid: 5d1f8b2c-3e7a-4a95-b6c0-7f2e9d4a1c83
# last-edited: 2026-09-11
"""Build PRIORITY-MATRIX.md (risk-ordered + effort-ordered) from merged.json.

Usage: build_matrix.py <state-dir> <out-md>
Rows: surviving REAL briefs, Wave 3 audit findings, and uncovered REAL TODO items
rolled up per TODO.md section, minus everything that merged since the 2026-09-10
freeze (see matrix_rows.build_rows). Re-runnable.
"""
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from matrix_rows import EFF_RANK, RISK_RANK, build_rows, effort_key, risk_key  # noqa: E402

STATE, OUT = sys.argv[1], sys.argv[2]
rows, done = build_rows(STATE)


def table(sorted_rows, limit=None):
    out = ["| # | Kind | Id | Brief | Risk | Sev | Effort | n | Title | Anchor / gate |", "|---|---|---|---|---|---|---|---|---|---|"]
    for i, r in enumerate(sorted_rows[:limit] if limit else sorted_rows, 1):
        gate = f" · **GATED: {r['gate']}**" if r["gate"] else ""
        brief = f"`{r['brief']}`" if r.get("brief") else "—"
        out.append(f"| {i} | {r['kind']} | `{r['id']}` | {brief} | {r['risk']} | {r['severity'] or '—'} | {r['effort']} | {r['count']} | {r['title']} | `{r['anchor']}`{gate} |")
    return "\n".join(out)


def done_table(done_rows):
    out = ["| Kind | Id | Brief | Risk | Title | Closed by |", "|---|---|---|---|---|---|"]
    for r in sorted(done_rows, key=risk_key):
        brief = f"`{r['brief']}`" if r.get("brief") else "—"
        out.append(f"| {r['kind']} | `{r['id']}` | {brief} | {r['risk']} | {r['title']} | {r['pr']} |")
    return "\n".join(out)


by_kind = collections.Counter(r["kind"] for r in rows)
by_risk = collections.Counter(r["risk"] for r in rows)
by_effort = collections.Counter(r["effort"] for r in rows)

md = f"""<!-- file: docs/agent-tasks/todo-completion-2026-09/PRIORITY-MATRIX.md -->
<!-- version: 1.4.0 -->
<!-- guid: 8e2c4f7a-1d5b-4b39-9a6e-3c8f0d2b7e41 -->
<!-- last-edited: 2026-09-11 -->

# Priority matrix — burndown 2026-09-10

Generated by `state/tools/build_matrix.py` from `state/merged.json`; regenerate, never
hand-edit. One row per unit of work: a surviving brief (`brief`), a Wave 3 audit
finding (`finding`), or a TODO.md section holding REAL items that no brief covers
(`todo-section`, `n` = open item count). `Brief` is the TASK id in this package that covers
the row (findings → TASK-300+, data-loss/security TODO sections → TASK-335+; carried briefs
are their own id); `—` means no brief yet — brief it on demand when the cut line reaches it.
Pick a cut line in either table; the two orderings are the same rows.

Rows that merged after the 2026-09-10 freeze are dropped: finding and brief ids come from
`state/final/done_since_0910.json` (append there when a PR merges), TODO items from the live
checkbox state of `TODO.md` (items are re-located by text because assembly shifts every line).
The same rows drawn as an impact-vs-effort chart: [QUADRANT.md](QUADRANT.md).

`GATED` rows: owner-gated sibling initiatives; `HOLD-FOR-OWNER` TODO sections whose
items are decisions or prod runs (`state/final/todo_sections_validation.json`); and `DEFER` /
`SUPERSEDED` rows from the design-fit review (`state/final/design_fit_rows_*.json`) — they stay
in the ranking so the cut line is complete, but they are not worker tasks.

**Rows: {len(rows)}** — {dict(by_kind)}. **Done since 2026-09-10: {len(done)}** (section C).
By risk: {dict(sorted(by_risk.items(), key=lambda kv: RISK_RANK.get(kv[0], 6)))}.
By effort: {dict(sorted(by_effort.items(), key=lambda kv: EFF_RANK.get(kv[0], 3)))}.

Risk order: data-loss → security → correctness → perf → ux → hygiene; within a risk,
severity (critical→low) then effort (S→L). Effort order: S → M → L; within an effort,
risk then severity. `GATED` rows are REAL but need an owner decision before dispatch.

## A. Risk-ordered (most dangerous first)

{table(sorted(rows, key=risk_key))}

## B. Effort-ordered (quickest wins first)

{table(sorted(rows, key=effort_key))}

## C. Done since the 2026-09-10 freeze

{done_table(done)}
"""
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(md)
print(f"rows={len(rows)} done={len(done)} kinds={dict(by_kind)} risk={dict(by_risk)} effort={dict(by_effort)}")
