#!/usr/bin/env python3
# file: docs/agent-tasks/todo-completion-2026-09/state/tools/build_reconciliation.py
# version: 1.0.0
# guid: a6e3d9c4-2b8f-4f17-9c50-6d1e4a7b2f98
# last-edited: 2026-09-10
"""Build RECONCILIATION-2026-09-10.md (DONE/STALE/REAL ledger with evidence).

Usage: build_reconciliation.py <state-dir> <out-md>
Every one of the 251 briefs and 586 TODO items gets exactly one row. Re-runnable.
"""
import collections
import json
import os
import sys

STATE, OUT = sys.argv[1], sys.argv[2]
d = json.load(open(os.path.join(STATE, "merged.json"), encoding="utf-8"))
S = d["summary"]

ICON = {"DONE": "✅", "STALE": "⏩", "REAL": "🟡", "UNCLEAR": "❓"}


def cell(s, n=160):
    s = (s or "").replace("|", "\\|").replace("\n", " ").strip()
    return s if len(s) <= n else s[: n - 1] + "…"


# ---- briefs by initiative/workstream ---------------------------------------
groups = collections.OrderedDict()
for b in sorted(d["briefs"], key=lambda b: b["path"]):
    parts = b["path"].split("/")
    key = parts[2] if parts[2] != "todo-completion" else f"todo-completion/{parts[3]}"
    groups.setdefault(key, []).append(b)

brief_sections = []
for key, rows in groups.items():
    c = collections.Counter(r["verdict"] for r in rows)
    brief_sections.append(f"\n#### {key} · {len(rows)} — " + ", ".join(f"{k.lower()} {v}" for k, v in sorted(c.items())))
    brief_sections.append("\n| Task | 09-02 | 09-10 | Evidence | Notes |\n|---|---|---|---|---|")
    for r in rows:
        flip = " **(flip)**" if r.get("changed_since_0902") else ""
        brief_sections.append(
            f"| {r['task_id']} | {cell(r.get('status_0902') or '—', 40)} | {ICON[r['verdict']]} {r['verdict']}{flip} | {cell(r.get('evidence'))} | {cell(r.get('notes'), 120)} |"
        )

# ---- TODO items by section --------------------------------------------------
todo_groups = collections.OrderedDict()
for t in d["todo"]:
    todo_groups.setdefault(t["section"], []).append(t)

todo_sections = []
for sec, rows in todo_groups.items():
    c = collections.Counter(r["verdict"] for r in rows)
    todo_sections.append(f"\n#### `{cell(sec, 90)}` · {len(rows)} — " + ", ".join(f"{k.lower()} {v}" for k, v in sorted(c.items())))
    todo_sections.append("\n| Line | Verdict | Item | Evidence | Brief |\n|---|---|---|---|---|")
    for r in rows:
        todo_sections.append(
            f"| {r['line']} | {ICON[r['verdict']]} {r['verdict']} | {cell(r.get('text_head'), 100)} | {cell(r.get('evidence'), 140)} | {r.get('dup_of') or '—'} |"
        )

flips = [b for b in d["briefs"] if b.get("changed_since_0902")]

md = f"""<!-- file: docs/agent-tasks/todo-completion-2026-09/RECONCILIATION-2026-09-10.md -->
<!-- version: 1.0.0 -->
<!-- guid: 4c9b1e7d-8a2f-4d63-b5e0-1f7c3a9d6b25 -->
<!-- last-edited: 2026-09-10 -->

# Reconciliation ledger — 2026-09-10

Generated by `state/tools/build_reconciliation.py` from `state/merged.json`; regenerate,
never hand-edit. Baseline HEAD `42d187168` (== `origin/main`); previous reconciliation
`d2fcef16a` (2026-09-02); 399 commits and 138 merged PRs in between. Raw agent outputs
and each agent's final report are under `state/` (`RAW-RESULTS.md`).

**Evidence rule.** `DONE` cites a merged PR / commit **and** a code check at HEAD;
`STALE` cites what removed or overturned the premise; `REAL` cites the file:line that
still shows the gap (each brief's own re-verify greps were re-run); `UNCLEAR` names
what a repo-only read could not settle (a prod observation, a live Playwright run).
A doc claim, a TODO.md line, or a commit message alone never counts.

## Totals

| Input | Total | ✅ DONE | ⏩ STALE | 🟡 REAL | ❓ UNCLEAR |
|---|---|---|---|---|---|
| Briefs (`docs/agent-tasks/**/TASK-*.md`) | {S['briefs_total']} | {S['briefs_by_verdict'].get('DONE', 0)} | {S['briefs_by_verdict'].get('STALE', 0)} | {S['briefs_by_verdict'].get('REAL', 0)} | {S['briefs_by_verdict'].get('UNCLEAR', 0)} |
| `TODO.md` unchecked items | {S['todo_total']} | {S['todo_by_verdict'].get('DONE', 0)} | {S['todo_by_verdict'].get('STALE', 0)} | {S['todo_by_verdict'].get('REAL', 0)} | {S['todo_by_verdict'].get('UNCLEAR', 0)} |

{S['todo_dup_of_brief']} REAL TODO items are the source line of a surviving brief (`Brief` column).
Brief verdicts that changed since 2026-09-02: **{len(flips)}** — {", ".join(f"{b['task_id']} {b.get('status_0902','')[:6].strip()}→{b['verdict']}" for b in flips)}.

## 1. Briefs ({S['briefs_total']})
{"".join(s + chr(10) for s in brief_sections)}
## 2. `TODO.md` items ({S['todo_total']})
{"".join(s + chr(10) for s in todo_sections)}
"""
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(md)
print(f"briefs={S['briefs_total']} todo={S['todo_total']} flips={len(flips)} -> {OUT}")
