#!/usr/bin/env python3
# file: docs/agent-tasks/todo-completion-2026-09/state/tools/build_matrix.py
# version: 1.0.0
# guid: 5d1f8b2c-3e7a-4a95-b6c0-7f2e9d4a1c83
# last-edited: 2026-09-10
"""Build PRIORITY-MATRIX.md (risk-ordered + effort-ordered) from merged.json.

Usage: build_matrix.py <state-dir> <out-md>
Rows: surviving REAL briefs, Wave 3 audit findings, and uncovered REAL TODO items
rolled up per TODO.md section. Re-runnable.
"""
import collections
import json
import os
import sys

STATE, OUT = sys.argv[1], sys.argv[2]
d = json.load(open(os.path.join(STATE, "merged.json"), encoding="utf-8"))

RISK_RANK = {"data-loss": 0, "security": 1, "correctness": 2, "perf": 3, "ux": 4, "hygiene": 5, "null": 6, None: 6}
SEV_RANK = {"critical": 0, "high": 1, "medium": 2, "low": 3, None: 4}
EFF_RANK = {"S": 0, "M": 1, "L": 2, None: 3, "null": 3}
GATED = {
    "docs/agent-tasks/torrent-relocation/": "parked (DECISIONS-PENDING row 2)",
    "docs/agent-tasks/ai-responses-migration/": "on hold (useResponsesAPI design)",
}

rows = []

# 1. surviving briefs
for b in d["briefs"]:
    if b["verdict"] != "REAL":
        continue
    gate = next((v for k, v in GATED.items() if b["path"].startswith(k)), None)
    rows.append({
        "kind": "brief",
        "id": b["task_id"] if b["initiative"] == "todo-completion" else f"{b['initiative']}/{b['task_id']}",
        "title": b["title"][:110],
        "risk": b.get("risk") or "hygiene",
        "severity": None,
        "effort": b.get("effort") or "M",
        "count": 1,
        "anchor": b["path"],
        "gate": gate,
    })

# 2. audit findings
for f in d["findings"]:
    rows.append({
        "kind": "finding",
        "id": f["id"],
        "title": f["title"][:110],
        "risk": f.get("risk") or "correctness",
        "severity": f.get("severity"),
        "effort": f.get("effort") or "M",
        "count": 1,
        "anchor": f"{f.get('file')}:{f.get('line')}",
        "gate": None,
    })

# 3. uncovered REAL TODO items, rolled up per section
sections = collections.defaultdict(list)
for t in d["todo"]:
    if t["verdict"] == "REAL" and not t.get("dup_of"):
        sections[t["section"]].append(t)
for sec, items in sections.items():
    worst = min(items, key=lambda t: RISK_RANK.get(t.get("risk"), 6))
    cheapest = min(items, key=lambda t: EFF_RANK.get(t.get("effort"), 3))
    rows.append({
        "kind": "todo-section",
        "id": f"TODO.md:{min(t['line'] for t in items)}",
        "title": sec[:110],
        "risk": worst.get("risk") or "hygiene",
        "severity": None,
        "effort": cheapest.get("effort") or "M",
        "count": len(items),
        "anchor": "lines " + ",".join(str(t["line"]) for t in sorted(items, key=lambda t: t["line"])[:6]) + (" …" if len(items) > 6 else ""),
        "gate": None,
    })


def risk_key(r):
    return (RISK_RANK.get(r["risk"], 6), SEV_RANK.get(r["severity"], 4), EFF_RANK.get(r["effort"], 3), r["id"])


def effort_key(r):
    return (EFF_RANK.get(r["effort"], 3), RISK_RANK.get(r["risk"], 6), SEV_RANK.get(r["severity"], 4), r["id"])


def table(sorted_rows, limit=None):
    out = ["| # | Kind | Id | Risk | Sev | Effort | n | Title | Anchor / gate |", "|---|---|---|---|---|---|---|---|---|"]
    for i, r in enumerate(sorted_rows[:limit] if limit else sorted_rows, 1):
        gate = f" · **GATED: {r['gate']}**" if r["gate"] else ""
        out.append(f"| {i} | {r['kind']} | `{r['id']}` | {r['risk']} | {r['severity'] or '—'} | {r['effort']} | {r['count']} | {r['title']} | `{r['anchor']}`{gate} |")
    return "\n".join(out)


by_kind = collections.Counter(r["kind"] for r in rows)
by_risk = collections.Counter(r["risk"] for r in rows)
by_effort = collections.Counter(r["effort"] for r in rows)

md = f"""<!-- file: docs/agent-tasks/todo-completion-2026-09/PRIORITY-MATRIX.md -->
<!-- version: 1.0.0 -->
<!-- guid: 8e2c4f7a-1d5b-4b39-9a6e-3c8f0d2b7e41 -->
<!-- last-edited: 2026-09-10 -->

# Priority matrix — burndown 2026-09-10

Generated by `state/tools/build_matrix.py` from `state/merged.json`; regenerate, never
hand-edit. One row per unit of work: a surviving brief (`brief`), a Wave 3 audit
finding (`finding`), or a TODO.md section holding REAL items that no brief covers
(`todo-section`, `n` = item count). Pick a cut line in either table; the two orderings
are the same rows.

**Rows: {len(rows)}** — {dict(by_kind)}.
By risk: {dict(sorted(by_risk.items(), key=lambda kv: RISK_RANK.get(kv[0], 6)))}.
By effort: {dict(sorted(by_effort.items(), key=lambda kv: EFF_RANK.get(kv[0], 3)))}.

Risk order: data-loss → security → correctness → perf → ux → hygiene; within a risk,
severity (critical→low) then effort (S→L). Effort order: S → M → L; within an effort,
risk then severity. `GATED` rows are REAL but need an owner decision before dispatch.

## A. Risk-ordered (most dangerous first)

{table(sorted(rows, key=risk_key))}

## B. Effort-ordered (quickest wins first)

{table(sorted(rows, key=effort_key))}
"""
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(md)
print(f"rows={len(rows)} kinds={dict(by_kind)} risk={dict(by_risk)} effort={dict(by_effort)}")
