#!/usr/bin/env python3
# file: docs/agent-tasks/todo-completion-2026-09/state/tools/build_quadrant.py
# version: 1.0.0
# guid: 9c4b2e7a-0d61-4f3e-8b5a-6e2d1c9f7a83
# last-edited: 2026-09-11
"""Build QUADRANT.md — every open row of the priority matrix on one impact-vs-effort chart.

Usage: build_quadrant.py <state-dir> <out-md>

Axes: x = effort (S is easy; M and L are hard), y = impact (data-loss, security and
correctness are large; perf, ux and hygiene are small). Inside each quadrant the rows
sit in horizontal bands by risk class (worst at the top) and are spread on a grid so
no two dots share a spot. Point labels are short mermaid-safe ids; the legend under
the chart maps each label to its title, class, effort and a GitHub link.
"""
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from matrix_rows import RISK_RANK, build_rows, easy, large_impact, risk_key, spread  # noqa: E402

STATE, OUT = sys.argv[1], sys.argv[2]
rows, done = build_rows(STATE)

# Vertical band per risk class, worst on top. The quadrant boundary is y = 0.5.
BANDS = {
    "data-loss": (0.80, 0.97),
    "security": (0.66, 0.79),
    "correctness": (0.53, 0.65),
    "perf": (0.34, 0.47),
    "ux": (0.20, 0.33),
    "hygiene": (0.03, 0.19),
}
# Horizontal band per effort. The quadrant boundary is x = 0.5; M and L both sit right of it.
X_BANDS = {"S": (0.03, 0.45), "M": (0.55, 0.74), "L": (0.78, 0.97)}

QUADRANTS = [
    ("q2", "Large impact · easy", lambda r: large_impact(r) and easy(r)),
    ("q1", "Large impact · hard", lambda r: large_impact(r) and not easy(r)),
    ("q3", "Small impact · easy", lambda r: not large_impact(r) and easy(r)),
    ("q4", "Small impact · hard", lambda r: not large_impact(r) and not easy(r)),
]

# Place every point: group by (effort, risk) cell, sort worst-first inside the cell.
placed = {}
cells = collections.defaultdict(list)
for r in rows:
    cells[(r["effort"], r["risk"])].append(r)
for (effort, risk), members in cells.items():
    members.sort(key=risk_key)
    x0, x1 = X_BANDS.get(effort, X_BANDS["M"])
    y0, y1 = BANDS.get(risk, BANDS["hygiene"])
    for r, xy in zip(members, spread(members, x0, x1, y0, y1)):
        placed[r["id"]] = xy


def mermaid():
    lines = [
        "```mermaid",
        '%%{init: {"quadrantChart": {"chartWidth": 1100, "chartHeight": 900, "pointRadius": 3, '
        '"pointLabelFontSize": 8, "quadrantPadding": 6, "xAxisLabelFontSize": 14, "yAxisLabelFontSize": 14, '
        '"quadrantLabelFontSize": 14}}}%%',
        "quadrantChart",
        "    title Open tasks by impact and effort (see legend for every label)",
        "    x-axis \"Easy to implement\" --> \"Hard to implement\"",
        "    y-axis \"Small impact\" --> \"Large impact\"",
        "    quadrant-1 \"Large impact, hard\"",
        "    quadrant-2 \"Large impact, easy\"",
        "    quadrant-3 \"Small impact, easy\"",
        "    quadrant-4 \"Small impact, hard\"",
    ]
    for r in sorted(rows, key=risk_key):
        x, y = placed[r["id"]]
        lines.append(f"    {r['label']}: [{x}, {y}]")
    lines.append("```")
    return "\n".join(lines)


def legend_entry(r):
    sev = f"/{r['severity']}" if r["severity"] else ""
    n = f", {r['count']} items" if r["kind"] == "todo-section" and r["count"] > 1 else ""
    gate = f" 🔒 **GATED:** {r['gate']}" if r["gate"] else ""
    brief = f" · brief `{r['brief']}`" if r.get("brief") and r["brief"] != r["id"] else ""
    return f"- **`{r['label']}`** [{r['title']}]({r['url']}) — {r['risk']}{sev}, effort {r['effort']}{n} · `{r['id']}`{brief}{gate}"


def legend():
    out = []
    for _, name, pred in QUADRANTS:
        members = sorted((r for r in rows if pred(r)), key=risk_key)
        gated = sum(1 for r in members if r["gate"])
        out.append(f"### {name} — {len(members)} rows ({gated} gated)\n")
        out.extend(legend_entry(r) for r in members)
        out.append("")
    return "\n".join(out)


by_q = {name: sum(1 for r in rows if pred(r)) for _, name, pred in QUADRANTS}
by_risk = collections.Counter(r["risk"] for r in rows)
by_effort = collections.Counter(r["effort"] for r in rows)
top = [r for r in sorted(rows, key=risk_key) if large_impact(r) and easy(r) and not r["gate"]][:12]

md = f"""<!-- file: docs/agent-tasks/todo-completion-2026-09/QUADRANT.md -->
<!-- version: 1.0.0 -->
<!-- guid: 6f1d3b8e-2a47-4c95-b0e3-9d7c5a2e1f60 -->
<!-- last-edited: 2026-09-11 -->

# Impact vs effort — every open task on one chart

Generated by `state/tools/build_quadrant.py` from the same rows as
[PRIORITY-MATRIX.md](PRIORITY-MATRIX.md); regenerate, never hand-edit:

```bash
python3 docs/agent-tasks/todo-completion-2026-09/state/tools/build_quadrant.py \\
    docs/agent-tasks/todo-completion-2026-09/state docs/agent-tasks/todo-completion-2026-09/QUADRANT.md
```

**How to read it.** Each dot is one unit of work: a brief (`T083` = TASK-083; `TR-03`, `AI-01`,
`UX-05`, `DD-06` are sibling-initiative briefs), an audit finding (`DA-04`, `CI-02`, …), or a
TODO.md section that no brief covers (`L1015` = the section whose first item was line 1015 at
the 2026-09-10 freeze). Right of the centre line = effort M or L; left = S. Above the centre
line = data-loss, security or correctness; below = perf, ux or hygiene. Inside a quadrant the
rows sit in bands by class, worst at the top, and are spread out only so the labels stay
readable — horizontal position inside a band carries no meaning. Gated rows (owner decision,
prod run, or a parked sibling initiative) are on the chart but marked 🔒 in the legend.

**{len(rows)} open rows** — {by_q}. Done since the 2026-09-10 freeze: {len(done)}
(listed in PRIORITY-MATRIX.md section C).
By class: {dict(sorted(by_risk.items(), key=lambda kv: RISK_RANK.get(kv[0], 6)))}.
By effort: {dict(sorted(by_effort.items(), key=lambda kv: {"S": 0, "M": 1, "L": 2}.get(kv[0], 3)))}.

{mermaid()}

## Start here — large impact, easy, not gated

{chr(10).join(legend_entry(r) for r in top)}

## Legend

Every label on the chart, grouped by quadrant and ordered worst-first (class, then severity,
then effort). Links open the brief, the finding's source line, or the section's first open
TODO.md line on `main`.

{legend()}
"""
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(md)
print(f"rows={len(rows)} done={len(done)} quadrants={by_q}")
